/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ConstantesAlmacenyTaller;
import Control.SentenciaSQL;
import Control.TipoProductoDAO;
import Control.Validaciones;
import Facade.FacadeComprobante;
import Modelo.ParametrosFactura;
import Modelo.Comprobante;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author jose luis Rodriguez
 */
public class ComprobanteGUI extends javax.swing.JDialog {

    Validaciones validaciones = new Validaciones();
    static ParametrosFactura parametrosFactura = new ParametrosFactura();
    ConstantesAlmacenyTaller constantes = new ConstantesAlmacenyTaller();
    SentenciaSQL sentencia = new SentenciaSQL();
    FacadeComprobante facadeComprobante = new FacadeComprobante();
    Comprobante comprobante = new Comprobante();
    /**
     * Creates new form ProductoGUI2
     */
    public ComprobanteGUI(java.awt.Frame parent, boolean modal, ParametrosFactura parametrosFactura) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Gestion Factura");
        
        this.parametrosFactura = parametrosFactura;
        productosFactura.setModel(parametrosFactura.getProductosaVender());
        numeroDocumentoClienteTxt.setText(parametrosFactura.getNumeroDocumentoCliente());
        nombresClienteTxt.setText(parametrosFactura.getNombreCliente());
        nombresEmpleadoTxt.setText(parametrosFactura.getNombreEmpleado());
        numeroDocumentoEmpleadoTxt.setText(parametrosFactura.getNumeroDocumentoEmpleado());
        calcularMontos();
                String queryCodigo = "select MAX(cod_comprobante) conteo from comprobante";
        
        ResultSet result = sentencia.gestionarConsulta(queryCodigo);
      
        idFacturaLbl.setText(sentencia.contarCodigos(result)+"");
        
        fechaFacturaDate.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        mensajeLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosFactura = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        valorTotalLbl = new javax.swing.JLabel();
        totalDescuentoLbl = new javax.swing.JLabel();
        subtotalLbl = new javax.swing.JLabel();
        ivaLbl = new javax.swing.JLabel();
        nombresClienteTxt = new javax.swing.JLabel();
        numeroDocumentoEmpleadoTxt = new javax.swing.JLabel();
        nombresEmpleadoTxt = new javax.swing.JLabel();
        numeroDocumentoClienteTxt = new javax.swing.JLabel();
        idFacturaLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaFacturaDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("Detalles de Factura");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imprimir.png"))); // NOI18N
        jButton1.setToolTipText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 99, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 120, 90));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprobante.png"))); // NOI18N
        jLabel8.setText("factura");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 230, 80));

        mensajeLbl.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        mensajeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(mensajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 350, 30));

        productosFactura.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        productosFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(productosFactura);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 150));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("Valor Total");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("Documento Cliente");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Nombres Empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel29.setText("Nombres Cliente");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel11.setText("Documento Empleado");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel12.setText("Total Descuento");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel13.setText("Subtotal");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel14.setText("Iva");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        valorTotalLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        valorTotalLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(valorTotalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 180, 26));

        totalDescuentoLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        totalDescuentoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(totalDescuentoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 180, 26));

        subtotalLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        subtotalLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(subtotalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 180, 26));

        ivaLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ivaLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(ivaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 180, 26));

        nombresClienteTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(nombresClienteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 240, 26));

        numeroDocumentoEmpleadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        numeroDocumentoEmpleadoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(numeroDocumentoEmpleadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 240, 26));

        nombresEmpleadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(nombresEmpleadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 240, 26));

        numeroDocumentoClienteTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        numeroDocumentoClienteTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(numeroDocumentoClienteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 240, 26));

        idFacturaLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        idFacturaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(idFacturaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 130, 26));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Fecha de Factura");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Id Factura");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        fechaFacturaDate.setEnabled(false);
        fechaFacturaDate.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(fechaFacturaDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 170, 26));

        jTabbedPane1.addTab("Facturación", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

                facadeComprobante.registrarComprobante(mapearComprobante());
                imprimirFactura();
                
                
    
        } catch (SQLException ex) {
            Logger.getLogger(ComprobanteGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ComprobanteGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(ComprobanteGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
  

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprobanteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprobanteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprobanteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprobanteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog.setDefaultLookAndFeelDecorated(true);
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessBlackSteelSkin");
                ComprobanteGUI dialog = new ComprobanteGUI(new javax.swing.JFrame(), true, parametrosFactura);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fechaFacturaDate;
    private javax.swing.JLabel idFacturaLbl;
    private javax.swing.JLabel ivaLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mensajeLbl;
    private javax.swing.JLabel nombresClienteTxt;
    private javax.swing.JLabel nombresEmpleadoTxt;
    private javax.swing.JLabel numeroDocumentoClienteTxt;
    private javax.swing.JLabel numeroDocumentoEmpleadoTxt;
    private javax.swing.JTable productosFactura;
    private javax.swing.JLabel subtotalLbl;
    private javax.swing.JLabel totalDescuentoLbl;
    private javax.swing.JLabel valorTotalLbl;
    // End of variables declaration//GEN-END:variables

    public void validarSonido(boolean flag) {
        if (flag) {
            getToolkit().beep();

        } else {

        }
    
        
     }

    public void calcularMontos(){
            double acumulaValorConjunto = 0;
            double acumulaDescuentos = 0;
          for (int i = 0; i < productosFactura.getRowCount(); i++) {
            acumulaValorConjunto = acumulaValorConjunto + Double.parseDouble(productosFactura.getValueAt(i, 4).toString());
            acumulaDescuentos = acumulaDescuentos + Double.parseDouble(productosFactura.getValueAt(i, 5).toString());
        }
          totalDescuentoLbl.setText(acumulaDescuentos+"");
          subtotalLbl.setText(validaciones.calcularSubTotal(acumulaValorConjunto, acumulaDescuentos)+"");
          ivaLbl.setText( validaciones.calcularIva(19, acumulaValorConjunto-acumulaDescuentos)+"");
          valorTotalLbl.setText(validaciones.calcularValorTotal(19, acumulaValorConjunto, acumulaDescuentos)+"");
            
    }
    
    public Comprobante mapearComprobante(){
    
            comprobante.setCodVenta(parametrosFactura.getCodigoVenta());
            comprobante.setDescuento(Double.parseDouble(totalDescuentoLbl.getText()));
            comprobante.setEstado(constantes.CONSTANTE_ESTADO_POR_DEFECTO);
            comprobante.setFechaComprobante(fechaFacturaDate.getDate());
            comprobante.setIva(Double.parseDouble(ivaLbl.getText()));
            comprobante.setValor(Double.parseDouble(subtotalLbl.getText()));
            comprobante.setValorTotal(Double.parseDouble(valorTotalLbl.getText()));
            
            return comprobante;
    
    }
    
    public void imprimirFactura() throws BadElementException, DocumentException{
            try {
            FileOutputStream archivoSalidaTexto = new FileOutputStream("D:\\Documentacio de proyecto\\Facturas\\factura"+idFacturaLbl.getText()+".pdf");
            Document documento = new Document(PageSize.A4,36,36,10,10);
            PdfWriter.getInstance(documento, archivoSalidaTexto);
            documento.open();
            Image imagen = Image.getInstance("D:\\Descargas\\motoRepuestos.png");
            imagen.setAlignment(Element.ALIGN_CENTER);
            imagen.scaleAbsolute(35, 35);
            documento.add(imagen);
            Paragraph p = new Paragraph();
            p.setAlignment(Element.ALIGN_CENTER);
            Paragraph nombreAlmacen = new Paragraph();
            nombreAlmacen.setAlignment(Element.ALIGN_CENTER);
            nombreAlmacen.add("MOTOREPUESTOS");
            documento.add(nombreAlmacen);
            documento.add(new Paragraph("\n\n"));
            
       
            p.add("-----------------------------------------FACTURA--------------------------------------");
            documento.add(p);
            documento.add(new Paragraph("\n\n"));
            
            PdfPTable tabla2 = new PdfPTable(2); 
    
    tabla2.setWidthPercentage(100);
    
    tabla2.setWidths(new float[] {10, 10});

    //Añadimos los títulos a la tabla. 
    Paragraph columnanombre = new Paragraph("NOMBRE EMPLEADO");
    columnanombre.getFont().setStyle(Font.BOLD);
    columnanombre.getFont().setSize(10);
    tabla2.addCell(columnanombre);
    
    Paragraph textonombre = new Paragraph(nombresEmpleadoTxt.getText());
    textonombre.getFont().setStyle(Font.BOLD);
    textonombre.getFont().setSize(10);
    tabla2.addCell(textonombre);

    Paragraph columnaDocumento = new Paragraph("NUMERO DOCUMENTO EMPLEADO");
    columnaDocumento.getFont().setStyle(Font.BOLD);
    columnaDocumento.getFont().setSize(10);
    tabla2.addCell(columnaDocumento);
    
    
 

    Paragraph textoDocumento = new Paragraph(numeroDocumentoEmpleadoTxt.getText());
    textoDocumento.getFont().setStyle(Font.BOLD);
    textoDocumento.getFont().setSize(10);
    tabla2.addCell(textoDocumento);
    
    
    
    
    
     Paragraph columnanombreCliente = new Paragraph("NOMBRE CLIENTE");
    columnanombreCliente.getFont().setStyle(Font.BOLD);
    columnanombreCliente.getFont().setSize(10);
    tabla2.addCell(columnanombreCliente);
    
    Paragraph textonombreCliente = new Paragraph(nombresClienteTxt.getText());
    textonombreCliente.getFont().setStyle(Font.BOLD);
    textonombreCliente.getFont().setSize(10);
    tabla2.addCell(textonombreCliente);

    Paragraph columnaDocumentoCliente = new Paragraph("NUMERO DOCUMENTO CLIENTE");
    columnaDocumentoCliente.getFont().setStyle(Font.BOLD);
    columnaDocumentoCliente.getFont().setSize(10);
    tabla2.addCell(columnaDocumentoCliente);
    
    
 

    Paragraph textoDocumentoEmpleado = new Paragraph(numeroDocumentoClienteTxt.getText());
    textoDocumentoEmpleado.getFont().setStyle(Font.BOLD);
    textoDocumentoEmpleado.getFont().setSize(10);
    tabla2.addCell(textoDocumentoEmpleado);
    documento.add(tabla2);

            documento.add(new Paragraph("FECHA DE FACTURACION:   "+validaciones.transformarFechatoString (fechaFacturaDate.getDate())));
            documento.add(new Paragraph("ID FACTURA:   "+idFacturaLbl.getText()));
            
      
            Paragraph detalles = new Paragraph();
            detalles.setAlignment(Element.ALIGN_CENTER);
            documento.add(new Paragraph("\n\n"));
            
            
            detalles.add("----------------------------------------- LISTADO DE PRODUCTOS --------------------------------------");
            documento.add(detalles);
            documento.add(new Paragraph("\n\n"));
            
            
            PdfPTable tabla = new PdfPTable(4); 
    
    tabla.setWidthPercentage(100);
    
    tabla.setWidths(new float[] {10, 10, 10, 10});

    //Añadimos los títulos a la tabla. 
    Paragraph columna1 = new Paragraph("NOMBRE");
    columna1.getFont().setStyle(Font.BOLD);
    columna1.getFont().setSize(10);
    tabla.addCell(columna1);

    Paragraph columna2 = new Paragraph("CANTIDAD");
    columna2.getFont().setStyle(Font.BOLD);
    columna2.getFont().setSize(10);
    tabla.addCell(columna2);

    Paragraph columna3 = new Paragraph("VALOR UNITARIO");
    columna3.getFont().setStyle(Font.BOLD);
    columna3.getFont().setSize(10);
    tabla.addCell(columna3);

    Paragraph columna4 = new Paragraph("DESCUENTO");
    columna4.getFont().setStyle(Font.BOLD);
    columna4.getFont().setSize(10);
    tabla.addCell(columna4);



     
    for (int i = 0; i < productosFactura.getRowCount(); i++){ 
        tabla.addCell(productosFactura.getValueAt(i, 1)+""); 
        tabla.addCell(productosFactura.getValueAt(i, 2)+""); 
        tabla.addCell(productosFactura.getValueAt(i, 3)+""); 
        tabla.addCell(productosFactura.getValueAt(i, 5)+""); 
        
    } 

    
    documento.add(tabla);   
            
            documento.add(new Paragraph("\n\n"));
            
             Paragraph detallesCierre = new Paragraph();
            detallesCierre.setAlignment(Element.ALIGN_CENTER);
           
            
            
            detallesCierre.add("----------------------------------------------------------------------------------------------------------------------------------");
            documento.add(detallesCierre);
            
            
            
            
            
            
            
                documento.add(new Paragraph("TOTAL DESCUENTOS:                    "+totalDescuentoLbl.getText()));
                documento.add(new Paragraph("SUB TOTAL:                                     "+subtotalLbl.getText()));
                documento.add(new Paragraph("IVA:                                                   "+ivaLbl.getText()));
                documento.add(new Paragraph("VALOR TOTAL:                                "+valorTotalLbl.getText()));                
            documento.close();
            File file = new File("D:\\Documentacio de proyecto\\Facturas\\factura"+idFacturaLbl.getText()+".pdf");
            Desktop.getDesktop().open(file);
            dispose();

        } catch (DocumentException | IOException e) {
        } catch (ParseException ex) {
            Logger.getLogger(ComprobanteGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
}
