/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ConstantesAlmacenyTaller;
import Control.ProductoDAO;


import Control.Validaciones;
import Facade.FacadeProveedor;

import Facade.FacadeEmpleado;
import Facade.FacadeCompra;
import Modelo.Proveedor;
import Control.DetalleCompraDAO;
import Modelo.DetalleCompra;

import Modelo.Empleado;
import Modelo.ParametrosFactura;

import Modelo.Persona;
import Modelo.Producto;

import Modelo.Compra;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;

import java.util.ArrayList;
import java.util.List;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JTable;

import javax.swing.table.DefaultTableModel;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author jose luis Rodriguez
 */
public class ComprarGUI extends javax.swing.JDialog {
    
    Validaciones validaciones = new Validaciones();
    ConstantesAlmacenyTaller constantes = new ConstantesAlmacenyTaller();
    FacadeEmpleado facadeEmpleado = new FacadeEmpleado();
    Empleado empleado;
    Persona persona = new Persona();
    Persona personaProveedor = new Persona();
    String columnasTablaProductos[] = {"ID","NOMBRE","PRECIO ACTUAL","STOCK"};
    String columnasTablaProductosSeleccionados[] = {"ID","NOMBRE","CANTIDAD","VLR UNIT","VLR CONJUNTO","DESCUENTO"};
    DefaultTableModel modeloTablaProductos = new DefaultTableModel();
    DefaultTableModel modeloTablaProductosSeleccionados = new DefaultTableModel();
    ProductoDAO productoDAO;
    List<Producto> listadoProducto = new ArrayList();
    double cantidadProductoSeleccionado;
    double valorProductoSeleccionado;
    double acumulaTotales = 0;
    double descuento = 0;
    int idProductoSeleccionado;
    Proveedor proveedor = new Proveedor();
    FacadeProveedor facadeProveedor = new FacadeProveedor();
    Compra compra = new Compra();
    FacadeCompra facadeCompra = new FacadeCompra();
    DetalleCompraDAO detalleCompraDAO = new DetalleCompraDAO();
    //int codigoVentaParametroFactura;
    

      
    /**
     * Creates new form MotocicletaGUI
     */
    public ComprarGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        
        registrarBtn.setEnabled(true);
        this.setTitle("Gestion Compras");
        this.setLocationRelativeTo(null);
        
        modeloTablaProductos.setColumnIdentifiers(columnasTablaProductos);
        modeloTablaProductosSeleccionados.setColumnIdentifiers(columnasTablaProductosSeleccionados);
        productosConsultaTabla.setModel(modeloTablaProductos);
        productosSeleccionadosTabla.setModel(modeloTablaProductosSeleccionados);
        registrarBtn.setEnabled(false);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nombresProveedorTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        numeroDocumentoEmpleadoTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nombresEmpleadoTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        numeroDocumentoProveedorTxt = new javax.swing.JTextField();
        fechaCompraDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productosConsultaTabla = new javax.swing.JTable();
        nombreProductoTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        productoSeleccionadoTxt = new javax.swing.JTextField();
        cantidadProductoSeleccionadoTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosSeleccionadosTabla = new javax.swing.JTable();
        descuentoProductoSeleccionadoTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalParcialLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        valorProductoSeleccionadoTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        registrarBtn = new javax.swing.JButton();
        consultarBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        mensajeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("Documento Representante Legal");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 10));

        nombresProveedorTxt.setEditable(false);
        nombresProveedorTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nombresProveedorTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        nombresProveedorTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresProveedorTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresProveedorTxtFocusLost(evt);
            }
        });
        nombresProveedorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresProveedorTxtActionPerformed(evt);
            }
        });
        nombresProveedorTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombresProveedorTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombresProveedorTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresProveedorTxtKeyTyped(evt);
            }
        });
        jPanel1.add(nombresProveedorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 200, -1));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setText("Fecha de Compra");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 10));

        jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel29.setText("Nombre Comercial");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        numeroDocumentoEmpleadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        numeroDocumentoEmpleadoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        numeroDocumentoEmpleadoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroDocumentoEmpleadoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroDocumentoEmpleadoTxtFocusLost(evt);
            }
        });
        numeroDocumentoEmpleadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDocumentoEmpleadoTxtActionPerformed(evt);
            }
        });
        numeroDocumentoEmpleadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroDocumentoEmpleadoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroDocumentoEmpleadoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDocumentoEmpleadoTxtKeyTyped(evt);
            }
        });
        jPanel1.add(numeroDocumentoEmpleadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("Documento Empleado");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        nombresEmpleadoTxt.setEditable(false);
        nombresEmpleadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nombresEmpleadoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        nombresEmpleadoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresEmpleadoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresEmpleadoTxtFocusLost(evt);
            }
        });
        nombresEmpleadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresEmpleadoTxtActionPerformed(evt);
            }
        });
        nombresEmpleadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombresEmpleadoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombresEmpleadoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresEmpleadoTxtKeyTyped(evt);
            }
        });
        jPanel1.add(nombresEmpleadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Nombres Empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("*");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, 10));

        numeroDocumentoProveedorTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        numeroDocumentoProveedorTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        numeroDocumentoProveedorTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroDocumentoProveedorTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroDocumentoProveedorTxtFocusLost(evt);
            }
        });
        numeroDocumentoProveedorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDocumentoProveedorTxtActionPerformed(evt);
            }
        });
        numeroDocumentoProveedorTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroDocumentoProveedorTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroDocumentoProveedorTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDocumentoProveedorTxtKeyTyped(evt);
            }
        });
        jPanel1.add(numeroDocumentoProveedorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, -1));

        fechaCompraDate.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(fechaCompraDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 26));

        jTabbedPane1.addTab("Datos de la Compra", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productosConsultaTabla.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        productosConsultaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        productosConsultaTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productosConsultaTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        productosConsultaTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosConsultaTablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(productosConsultaTabla);
        productosConsultaTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 80));

        nombreProductoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nombreProductoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        nombreProductoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreProductoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreProductoTxtFocusLost(evt);
            }
        });
        nombreProductoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoTxtActionPerformed(evt);
            }
        });
        nombreProductoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreProductoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreProductoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreProductoTxtKeyTyped(evt);
            }
        });
        jPanel2.add(nombreProductoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel11.setText("Cantidad");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        productoSeleccionadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        productoSeleccionadoTxt.setEnabled(false);
        jPanel2.add(productoSeleccionadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 26));

        cantidadProductoSeleccionadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cantidadProductoSeleccionadoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidadProductoSeleccionadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadProductoSeleccionadoTxtActionPerformed(evt);
            }
        });
        cantidadProductoSeleccionadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadProductoSeleccionadoTxtKeyTyped(evt);
            }
        });
        jPanel2.add(cantidadProductoSeleccionadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 60, 26));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel12.setText("Nombre producto");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel13.setText("Producto Seleccionado");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, 10));

        productosSeleccionadosTabla.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        productosSeleccionadosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(productosSeleccionadosTabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 110));

        descuentoProductoSeleccionadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        descuentoProductoSeleccionadoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        descuentoProductoSeleccionadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descuentoProductoSeleccionadoTxtActionPerformed(evt);
            }
        });
        descuentoProductoSeleccionadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descuentoProductoSeleccionadoTxtKeyTyped(evt);
            }
        });
        jPanel2.add(descuentoProductoSeleccionadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, 26));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel14.setText("Descuento");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("%");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 10, 20));

        totalParcialLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel2.add(totalParcialLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 366, 140, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrarRegistro.png"))); // NOI18N
        jButton1.setToolTipText("ELIMINAR REGISTRO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        valorProductoSeleccionadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        valorProductoSeleccionadoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorProductoSeleccionadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorProductoSeleccionadoTxtKeyTyped(evt);
            }
        });
        jPanel2.add(valorProductoSeleccionadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, 26));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel15.setText("Valor Und");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("*");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, 10));

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel17.setText("Total Parcial");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jTabbedPane1.addTab("Añadir Productos", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 430));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprar.png"))); // NOI18N
        jLabel1.setText("Comprar");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 230, 100));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        registrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        registrarBtn.setToolTipText("GUARDAR");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });
        jPanel3.add(registrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 145, 55));

        consultarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        consultarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        consultarBtn.setToolTipText("CONSULTAR");
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });
        jPanel3.add(consultarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 145, 60));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        jButton3.setToolTipText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 145, 55));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 160, 290));

        mensajeLbl.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        mensajeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mensajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 410, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresProveedorTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresProveedorTxtFocusGained

        validaciones.validarEnfoque(nombresProveedorTxt);
    }//GEN-LAST:event_nombresProveedorTxtFocusGained

    private void nombresProveedorTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresProveedorTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(nombresProveedorTxt));

  
        
    }//GEN-LAST:event_nombresProveedorTxtFocusLost

    private void nombresProveedorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresProveedorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresProveedorTxtActionPerformed

    private void nombresProveedorTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresProveedorTxtKeyPressed

    }//GEN-LAST:event_nombresProveedorTxtKeyPressed

    private void nombresProveedorTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresProveedorTxtKeyReleased

    }//GEN-LAST:event_nombresProveedorTxtKeyReleased

    private void nombresProveedorTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresProveedorTxtKeyTyped

        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, nombresProveedorTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_nombresProveedorTxtKeyTyped

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        
       
        try {
            persona = new Persona();
            personaProveedor = new Persona();
            empleado = new Empleado();
            if (!validaciones.validarCampoVacio(numeroDocumentoEmpleadoTxt) &&
                !validaciones.validarCampoVacio(numeroDocumentoProveedorTxt)) {
             persona.setNumeroDocumento(numeroDocumentoEmpleadoTxt.getText());
             personaProveedor.setNumeroDocumento(numeroDocumentoProveedorTxt.getText()); 
            }
            
            
            empleado.setPersona(persona);
            proveedor.setPersona(personaProveedor);
            if (validaciones.validarCamposCompra(numeroDocumentoEmpleadoTxt, numeroDocumentoProveedorTxt,
                fechaCompraDate, productosSeleccionadosTabla).equals("") &&
                facadeEmpleado.consultarEmpleado(empleado) != null &&
                facadeProveedor.consultarProveedor(proveedor) != null) {
                
                proveedor = facadeProveedor.consultarProveedor(proveedor);
                empleado = facadeEmpleado.consultarEmpleado(empleado);
                int codigoCompra = facadeCompra.registrarCompra(mapeoCompra(compra));
                registrarDetalleCompra(productosSeleccionadosTabla,codigoCompra);
                mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_REGISTRO_EXITOSO);
                
                registrarBtn.setEnabled(false);
                
                mensajeLbl.setForeground(Color.green);
                limpiarCampos();
                //ComprobanteGUI comprobanteGUI = new ComprobanteGUI(null, true, mapearParametrosFactura());
                
                //comprobanteGUI.setVisible(true);
             
        }else{
                if (!validaciones.validarCamposCompra(numeroDocumentoEmpleadoTxt, numeroDocumentoProveedorTxt,
                    fechaCompraDate, productosSeleccionadosTabla).equals("")) {
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_POR_DEFECTO);
                }else if(facadeEmpleado.consultarEmpleado(empleado) == null){
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_NO_EXISTE_REGISTRO);
                }else if(facadeProveedor.consultarProveedor(proveedor) == null){
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_NO_EXISTE_REGISTRO);
                }
                mensajeLbl.setForeground(Color.red);
                    
    }
            validaciones.notificarMensajeconTimer(mensajeLbl);

    }   catch (SQLException | ParseException ex) {
            Logger.getLogger(EmpleadoGUI.class.getName()).log(Level.SEVERE, null, ex);
            mensajeLbl.setForeground(Color.red);
            mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_ERROR_CONTROLADO);
        }
        validaciones.notificarMensajeconTimer(mensajeLbl);
          
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void numeroDocumentoEmpleadoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtFocusGained
        validaciones.validarEnfoque(numeroDocumentoEmpleadoTxt);
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtFocusGained

    private void numeroDocumentoEmpleadoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtFocusLost
        validarSonido(validaciones.validarCampoVacio(numeroDocumentoEmpleadoTxt));
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtFocusLost

    private void numeroDocumentoEmpleadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtActionPerformed

    private void numeroDocumentoEmpleadoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtKeyPressed

    private void numeroDocumentoEmpleadoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtKeyReleased

    private void numeroDocumentoEmpleadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, numeroDocumentoEmpleadoTxt));
        validaciones.validarCantidadCaracteresTexto(evt, numeroDocumentoEmpleadoTxt,
            constantes.CONSTANTE_CARACTERES_POR_LINEA);
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtKeyTyped

    private void nombresEmpleadoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtFocusGained

       
    }//GEN-LAST:event_nombresEmpleadoTxtFocusGained

    private void nombresEmpleadoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtFocusLost

       
    }//GEN-LAST:event_nombresEmpleadoTxtFocusLost

    private void nombresEmpleadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresEmpleadoTxtActionPerformed

    private void nombresEmpleadoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtKeyPressed

    }//GEN-LAST:event_nombresEmpleadoTxtKeyPressed

    private void nombresEmpleadoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtKeyReleased

    }//GEN-LAST:event_nombresEmpleadoTxtKeyReleased

    private void nombresEmpleadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, nombresEmpleadoTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, nombresEmpleadoTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_nombresEmpleadoTxtKeyTyped

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
        
        try {
            persona = new Persona();
            personaProveedor = new Persona();
            empleado = new Empleado();
            if (!validaciones.validarCampoVacio(numeroDocumentoEmpleadoTxt) &&
                !validaciones.validarCampoVacio(numeroDocumentoProveedorTxt)) {
             persona.setNumeroDocumento(numeroDocumentoEmpleadoTxt.getText());
             personaProveedor.setNumeroDocumento(numeroDocumentoProveedorTxt.getText()); 
             proveedor.setPersona(personaProveedor);
             empleado.setPersona(persona);
            
            
            if (facadeEmpleado.consultarEmpleado(empleado) != null &&
                facadeProveedor.consultarProveedor(proveedor) != null) {
                
                empleado = facadeEmpleado.consultarEmpleado(empleado);
                
                proveedor = facadeProveedor.consultarProveedor(proveedor);
                nombresEmpleadoTxt.setText(empleado.getPersona().getNombres().trim()+
                        " "+empleado.getPersona().getApellidos().trim());
                nombresProveedorTxt.setText(proveedor.getRazonSocial().trim());
         
                    registrarBtn.setEnabled(true);
                
                
                


            }else{
                if (!validaciones.validarCampoVacio(numeroDocumentoEmpleadoTxt)) {
                    registrarBtn.setEnabled(false);
                   

                }
                
                if (facadeEmpleado.consultarEmpleado(empleado) == null ) {
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_EMPLEADO_NO_EXISTE);
                    mensajeLbl.setForeground(Color.red);
                    
                }
                
                if (facadeProveedor.consultarProveedor(proveedor) == null ) {
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_NO_EXISTE_PROVEEDOR);
                    mensajeLbl.setForeground(Color.red);
                    
                }

            }
            }
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(EmpleadoGUI.class.getName()).log(Level.SEVERE, null, ex);
            mensajeLbl.setForeground(Color.red);
            mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_ERROR_CONTROLADO);
        }
        validaciones.notificarMensajeconTimer(mensajeLbl);
    }//GEN-LAST:event_consultarBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusGained

    private void numeroDocumentoProveedorTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoProveedorTxtFocusGained
        validaciones.validarEnfoque(numeroDocumentoProveedorTxt);
    }//GEN-LAST:event_numeroDocumentoProveedorTxtFocusGained

    private void numeroDocumentoProveedorTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoProveedorTxtFocusLost
        validarSonido(validaciones.validarCampoVacio(numeroDocumentoProveedorTxt));
    }//GEN-LAST:event_numeroDocumentoProveedorTxtFocusLost

    private void numeroDocumentoProveedorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDocumentoProveedorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoProveedorTxtActionPerformed

    private void numeroDocumentoProveedorTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoProveedorTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoProveedorTxtKeyPressed

    private void numeroDocumentoProveedorTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoProveedorTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoProveedorTxtKeyReleased

    private void numeroDocumentoProveedorTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoProveedorTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, numeroDocumentoProveedorTxt));
        validaciones.validarCantidadCaracteresTexto(evt, numeroDocumentoProveedorTxt,
            constantes.CONSTANTE_CARACTERES_POR_LINEA);
    }//GEN-LAST:event_numeroDocumentoProveedorTxtKeyTyped

    private void nombreProductoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreProductoTxtFocusGained

        validaciones.validarEnfoque(nombreProductoTxt);
    }//GEN-LAST:event_nombreProductoTxtFocusGained

    private void nombreProductoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreProductoTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(nombreProductoTxt));
    }//GEN-LAST:event_nombreProductoTxtFocusLost

    private void nombreProductoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProductoTxtActionPerformed
        productoDAO = new ProductoDAO();
        
        try {
            listadoProducto = productoDAO.consultarProducto(nombreProductoTxt.getText());
            if (listadoProducto != null) {
                productosConsultaTabla.setModel(validaciones.asignarModeloTabla(modeloTablaProductos, listadoProducto));
            }else{
                mensajeLbl.setForeground(Color.red);
                mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_NO_EXISTEN_PRODUCTOS);
                validaciones.notificarMensajeconTimer(mensajeLbl);
                DefaultTableModel auxModelo = new DefaultTableModel();
                auxModelo.setColumnIdentifiers(columnasTablaProductos);
                productosConsultaTabla.setModel(auxModelo);
                productoSeleccionadoTxt.setText("");
                descuentoProductoSeleccionadoTxt.setText("");
                cantidadProductoSeleccionadoTxt.setText("");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ComprarGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nombreProductoTxtActionPerformed

    private void nombreProductoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreProductoTxtKeyPressed

    }//GEN-LAST:event_nombreProductoTxtKeyPressed

    private void nombreProductoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreProductoTxtKeyReleased

    }//GEN-LAST:event_nombreProductoTxtKeyReleased

    private void nombreProductoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreProductoTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, nombreProductoTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, nombreProductoTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_nombreProductoTxtKeyTyped

    private void productosConsultaTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosConsultaTablaMouseClicked
        
     productoSeleccionadoTxt.setText(productosConsultaTabla.getValueAt(productosConsultaTabla.getSelectedRow(), 1).toString());
     //cantidadProductoSeleccionado =  Double.parseDouble(productosConsultaTabla.getValueAt(productosConsultaTabla.getSelectedRow(), 3).toString());
     valorProductoSeleccionado =  Double.parseDouble(productosConsultaTabla.getValueAt(productosConsultaTabla.getSelectedRow(), 2).toString());
     idProductoSeleccionado =  Integer.parseInt(productosConsultaTabla.getValueAt(productosConsultaTabla.getSelectedRow(), 0).toString());
     cantidadProductoSeleccionadoTxt.setText("");
     descuentoProductoSeleccionadoTxt.setText("");
     valorProductoSeleccionadoTxt.setText("");
  
    }//GEN-LAST:event_productosConsultaTablaMouseClicked

    private void cantidadProductoSeleccionadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadProductoSeleccionadoTxtActionPerformed
        
        if (cantidadProductoSeleccionadoTxt.getText().trim().equals("") ||
            Double.parseDouble(cantidadProductoSeleccionadoTxt.getText()) < 1 ||
            valorProductoSeleccionadoTxt.getText().trim().equals("") ||
            Double.parseDouble(valorProductoSeleccionadoTxt.getText()) < 1) {
            
            mensajeLbl.setForeground(Color.red);
            mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_CANTIDAD_DE_PRODUCTOS_NO_DISPONIBLE);
            validaciones.notificarMensajeconTimer(mensajeLbl);
        }else{
            System.out.println("cantidad"+cantidadProductoSeleccionadoTxt.getText());
            if (descuentoProductoSeleccionadoTxt.getText().trim().equals("") ) {
                descuentoProductoSeleccionadoTxt.setText("0");
            }
            



            if (!validaciones.validarNombreProducto(productosSeleccionadosTabla, productoSeleccionadoTxt)) {
                    mapeoProductoSeleccionado();
                    calcularValorParcial();
                }else{
                    mensajeLbl.setForeground(Color.red);
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_PRODUCTO_SELECCIONADO);
                    validaciones.notificarMensajeconTimer(mensajeLbl);
                }
            
            
        }
    }//GEN-LAST:event_cantidadProductoSeleccionadoTxtActionPerformed

    private void cantidadProductoSeleccionadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadProductoSeleccionadoTxtKeyTyped
        validaciones.validarSoloNumerosConEnter(evt, cantidadProductoSeleccionadoTxt);
    }//GEN-LAST:event_cantidadProductoSeleccionadoTxtKeyTyped

    private void descuentoProductoSeleccionadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descuentoProductoSeleccionadoTxtActionPerformed

    }//GEN-LAST:event_descuentoProductoSeleccionadoTxtActionPerformed

    private void descuentoProductoSeleccionadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descuentoProductoSeleccionadoTxtKeyTyped
        validaciones.validarSoloNumerosConEnter(evt, descuentoProductoSeleccionadoTxt);
        validaciones.validarCantidadCaracteresTexto(evt, descuentoProductoSeleccionadoTxt, 2);
    }//GEN-LAST:event_descuentoProductoSeleccionadoTxtKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (productosSeleccionadosTabla.getSelectedRow() > -1) {
            modeloTablaProductosSeleccionados.removeRow(productosSeleccionadosTabla.getSelectedRow());
            calcularValorParcial();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void valorProductoSeleccionadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorProductoSeleccionadoTxtKeyTyped
        validaciones.validarSoloNumerosConEnter(evt, valorProductoSeleccionadoTxt);
    }//GEN-LAST:event_valorProductoSeleccionadoTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog.setDefaultLookAndFeelDecorated(true); 
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessBlackSteelSkin");
                ComprarGUI dialog = new ComprarGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadProductoSeleccionadoTxt;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JTextField descuentoProductoSeleccionadoTxt;
    private com.toedter.calendar.JDateChooser fechaCompraDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mensajeLbl;
    private javax.swing.JTextField nombreProductoTxt;
    private javax.swing.JTextField nombresEmpleadoTxt;
    private javax.swing.JTextField nombresProveedorTxt;
    private javax.swing.JTextField numeroDocumentoEmpleadoTxt;
    private javax.swing.JTextField numeroDocumentoProveedorTxt;
    private javax.swing.JTextField productoSeleccionadoTxt;
    private javax.swing.JTable productosConsultaTabla;
    private javax.swing.JTable productosSeleccionadosTabla;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JLabel totalParcialLbl;
    private javax.swing.JTextField valorProductoSeleccionadoTxt;
    // End of variables declaration//GEN-END:variables

     public void validarSonido(boolean flag){
         if (flag) {
              getToolkit().beep();
             
         }else{
             
         }
     } 
     
     public Compra mapeoCompra(Compra compra){
         compra = new Compra();
         compra.setProveedor(proveedor);
         compra.setEmpleado(empleado);
        
         
         compra.setEstado(constantes.CONSTANTE_ESTADO_POR_DEFECTO);
         compra.setCodProveedor(proveedor.getCodProveedor());
         compra.setCodEmpleado(empleado.getCodEmpleado());
         compra.setFechaCompra(fechaCompraDate.getDate());
         compra.setValorTotal(0.0);
         
         
        return compra;

     }
     
     
     public void mapeoProductoSeleccionado(){
     
                Object[] productoAgregar = new Object[6];
                productoAgregar[0] = idProductoSeleccionado;
                productoAgregar[1] = productoSeleccionadoTxt.getText().trim();
                productoAgregar[2] = cantidadProductoSeleccionadoTxt.getText();
                productoAgregar[3] = valorProductoSeleccionadoTxt.getText().trim();
                productoAgregar[4] = (Double.parseDouble(valorProductoSeleccionadoTxt.getText().trim())) * Double.parseDouble(cantidadProductoSeleccionadoTxt.getText());
                productoAgregar[5] = ((Double.parseDouble(descuentoProductoSeleccionadoTxt.getText().trim()))* Double.parseDouble(productoAgregar[4].toString())) / 100;
                modeloTablaProductosSeleccionados.addRow(productoAgregar);
                productosSeleccionadosTabla.setModel(modeloTablaProductosSeleccionados);
     
     }
     
     public void registrarDetalleCompra(JTable productos, int codigoCompra) throws SQLException, ParseException{
         
         for (int i = 0; i < productos.getRowCount(); i++) {
             DetalleCompra detalleCompra = new DetalleCompra();
             detalleCompra.setCodCompra(codigoCompra);
             detalleCompra.setCantidadProducto(Integer.parseInt(productos.getValueAt(i, 2).toString()));
             detalleCompra.setCodProducto(Integer.parseInt(productos.getValueAt(i, 0).toString()));
             detalleCompra.setDescuento(Double.parseDouble(productos.getValueAt(i, 5).toString()));
             detalleCompra.setValorConjunto(Double.parseDouble(productos.getValueAt(i, 4).toString()));
             detalleCompra.setValorUnitario(Double.parseDouble(productos.getValueAt(i, 3).toString()));
             
             detalleCompraDAO.registrarDetalleCompra(detalleCompra);
             Producto producto = new Producto();
             producto.setCodProducto(detalleCompra.getCodProducto());
             String parametroModificacion =  "+"+productos.getValueAt(i, 2).toString();
             productoDAO.actualizarStock(producto, parametroModificacion);
         }
         compra.setCodCompra(codigoCompra);
         compra.setValorTotal(Double.parseDouble(totalParcialLbl.getText()));
         facadeCompra.modificarCompra(compra);
         //codigoCompraParametroFactura = codigoVenta;
         
         

         
         
     
     }

    public void calcularValorParcial() {
                      acumulaTotales = 0;
                    descuento = 0;
                    for (int i = 0; i < productosSeleccionadosTabla.getRowCount() ; i++) {
                    descuento = descuento + Double.parseDouble(productosSeleccionadosTabla.getValueAt(i, 5).toString());
                    acumulaTotales = acumulaTotales + Double.parseDouble(productosSeleccionadosTabla.getValueAt(i, 3).toString()) * Double.parseDouble(productosSeleccionadosTabla.getValueAt(i, 2).toString());
                    
                }
                totalParcialLbl.setText(validaciones.calcularValorTotal(19, acumulaTotales, descuento)+"");
    }
    
    
    public ParametrosFactura mapearParametrosFactura(){
                ParametrosFactura parametrosFactura = new ParametrosFactura();
                parametrosFactura.setNombreCliente(nombresProveedorTxt.getText());
                parametrosFactura.setNombreEmpleado(nombresEmpleadoTxt.getText());
                parametrosFactura.setNumeroDocumentoCliente(numeroDocumentoProveedorTxt.getText());
                parametrosFactura.setNumeroDocumentoEmpleado(numeroDocumentoEmpleadoTxt.getText());
                parametrosFactura.setProductosaVender(modeloTablaProductosSeleccionados);
                //parametrosFactura.setCodigoVenta(codigoVentaParametroFactura);
    return parametrosFactura;
    }

    
    private void limpiarCampos() {
        numeroDocumentoEmpleadoTxt.setText("");
        nombresEmpleadoTxt.setText("");
        numeroDocumentoProveedorTxt.setText("");
        nombresProveedorTxt.setText("");
        fechaCompraDate.setDate(null);
        nombreProductoTxt.setText("");
        productoSeleccionadoTxt.setText("");
        valorProductoSeleccionadoTxt.setText("");
        descuentoProductoSeleccionadoTxt.setText("");
        cantidadProductoSeleccionadoTxt.setText("");
        modeloTablaProductos = new DefaultTableModel();
        modeloTablaProductosSeleccionados = new DefaultTableModel();
        modeloTablaProductos.setColumnIdentifiers(columnasTablaProductos);
        modeloTablaProductosSeleccionados.setColumnIdentifiers(columnasTablaProductosSeleccionados);
        productosConsultaTabla.setModel(modeloTablaProductos);
        productosSeleccionadosTabla.setModel(modeloTablaProductosSeleccionados);
        totalParcialLbl.setText("");
    }
    
}
