/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ConstantesAlmacenyTaller;

import Control.TipoDocumentoDAO;
import Control.Validaciones;
import Facade.FacadeEmpleado;
import Facade.FacadePersona;
import Modelo.Empleado;
import Modelo.Persona;
import java.awt.Color;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JDialog;


import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author jose luis Rodriguez
 */
public class EmpleadoGUI extends javax.swing.JDialog {
    
    Validaciones validaciones = new Validaciones();
    TipoDocumentoDAO tipoDocumentoDAO = new TipoDocumentoDAO();
    ConstantesAlmacenyTaller constantes = new ConstantesAlmacenyTaller();
    FacadeEmpleado facadeEmpleado = new FacadeEmpleado();
    Empleado empleado = new Empleado();
    Persona persona = new Persona();
    
    /**
     * Creates new form EmpleadoGUI
     */
    public EmpleadoGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        validaciones.adicionarItems(tipoDocumentoCombo,
        tipoDocumentoDAO.consultarTiposDocumento());
        this.setTitle("Gestion Empleados");
        this.setLocationRelativeTo(null);
        cualLbl.setVisible(false);
        ciudadEmpleadoTxt.setVisible(false);
        buttonGroupGenero.add(jRadioButtonFemenino);
        buttonGroupGenero.add(jRadioButtonMasculino);
        registrarBtn.setEnabled(false);
        modificarBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGenero = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nombresTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        apellidosTxt = new javax.swing.JTextField();
        direccionTxt = new javax.swing.JTextField();
        tipoDocumentoCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        numeroDocumentoTxt = new javax.swing.JTextField();
        celularTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fechaNacimientoDate = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        estadoCivilCombo = new javax.swing.JComboBox<>();
        fechaIngresoDate = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ciudadCombo = new javax.swing.JComboBox<>();
        cualLbl = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ciudadEmpleadoTxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jRadioButtonFemenino = new javax.swing.JRadioButton();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        mensajeLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        registrarBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        consultarBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombresTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nombresTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        nombresTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresTxtFocusLost(evt);
            }
        });
        nombresTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresTxtActionPerformed(evt);
            }
        });
        nombresTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombresTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombresTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresTxtKeyTyped(evt);
            }
        });
        jPanel1.add(nombresTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("Apellidos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, 10));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Nombres");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, 10));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setText("Dirección");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 10));

        telefonoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        telefonoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        telefonoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoTxtFocusLost(evt);
            }
        });
        telefonoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTxtActionPerformed(evt);
            }
        });
        telefonoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyTyped(evt);
            }
        });
        jPanel1.add(telefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 180, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setText("Celular");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        apellidosTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        apellidosTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        apellidosTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apellidosTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apellidosTxtFocusLost(evt);
            }
        });
        apellidosTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosTxtActionPerformed(evt);
            }
        });
        apellidosTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apellidosTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                apellidosTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidosTxtKeyTyped(evt);
            }
        });
        jPanel1.add(apellidosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        direccionTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        direccionTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        direccionTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                direccionTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                direccionTxtFocusLost(evt);
            }
        });
        direccionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTxtActionPerformed(evt);
            }
        });
        direccionTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                direccionTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                direccionTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionTxtKeyTyped(evt);
            }
        });
        jPanel1.add(direccionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 180, -1));

        tipoDocumentoCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tipoDocumentoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --" }));
        tipoDocumentoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoDocumentoComboItemStateChanged(evt);
            }
        });
        tipoDocumentoCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tipoDocumentoComboFocusLost(evt);
            }
        });
        tipoDocumentoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDocumentoComboActionPerformed(evt);
            }
        });
        jPanel1.add(tipoDocumentoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("Numero de Documento");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, 10));

        numeroDocumentoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        numeroDocumentoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        numeroDocumentoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroDocumentoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroDocumentoTxtFocusLost(evt);
            }
        });
        numeroDocumentoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDocumentoTxtActionPerformed(evt);
            }
        });
        numeroDocumentoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroDocumentoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroDocumentoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDocumentoTxtKeyTyped(evt);
            }
        });
        jPanel1.add(numeroDocumentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, -1));

        celularTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        celularTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        celularTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                celularTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                celularTxtFocusLost(evt);
            }
        });
        celularTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularTxtActionPerformed(evt);
            }
        });
        celularTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                celularTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                celularTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celularTxtKeyTyped(evt);
            }
        });
        jPanel1.add(celularTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("Tipo de Documento");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel11.setText("Telefono");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, 10));

        jTabbedPane1.addTab("Información Personal", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(fechaNacimientoDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 180, 24));

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel18.setText("Fecha de Ingreso");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 10));

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel20.setText("Estado Civil");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        estadoCivilCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        estadoCivilCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "SOLTERO", "CASADO", "UNION LIBRE" }));
        estadoCivilCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoCivilComboItemStateChanged(evt);
            }
        });
        estadoCivilCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                estadoCivilComboFocusLost(evt);
            }
        });
        estadoCivilCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCivilComboActionPerformed(evt);
            }
        });
        jPanel2.add(estadoCivilCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 180, -1));
        jPanel2.add(fechaIngresoDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 24));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setText("Fecha de Nacimiento");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, 10));

        ciudadCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ciudadCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "BOGOTA", "MEDELLIN", "CALI", "BARRANQUILLA", "CARTAGENA DE INDIAS", "SOLEDAD", "CUCUTA", "IBAGUE", "SOACHA", "BUCARAMANGA", "OTRA" }));
        ciudadCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ciudadComboItemStateChanged(evt);
            }
        });
        ciudadCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ciudadComboFocusLost(evt);
            }
        });
        ciudadCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadComboActionPerformed(evt);
            }
        });
        jPanel2.add(ciudadCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, -1));

        cualLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        cualLbl.setText("Cual?");
        jPanel2.add(cualLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 10));

        ciudadEmpleadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ciudadEmpleadoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        ciudadEmpleadoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ciudadEmpleadoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ciudadEmpleadoTxtFocusLost(evt);
            }
        });
        ciudadEmpleadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadEmpleadoTxtActionPerformed(evt);
            }
        });
        ciudadEmpleadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ciudadEmpleadoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ciudadEmpleadoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ciudadEmpleadoTxtKeyTyped(evt);
            }
        });
        jPanel2.add(ciudadEmpleadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 180, -1));

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel25.setText("Genero");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel26.setText("Ciudad");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jRadioButtonFemenino.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jRadioButtonFemenino.setText("Femenino");
        jPanel2.add(jRadioButtonFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jRadioButtonMasculino.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jRadioButtonMasculino.setText("Masculino");
        jPanel2.add(jRadioButtonMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jTabbedPane1.addTab("Información Laboral", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 600, 350));

        jLabel12.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados.png"))); // NOI18N
        jLabel12.setText("Empleados");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 270, 80));

        mensajeLbl.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        mensajeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mensajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 350, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        registrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        registrarBtn.setToolTipText("REGISTRAR");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });
        jPanel3.add(registrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 145, 55));

        modificarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        modificarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        modificarBtn.setToolTipText("MODIFICAR");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });
        jPanel3.add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 145, 55));

        consultarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        consultarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        consultarBtn.setToolTipText("CONSULTAR");
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });
        jPanel3.add(consultarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 145, 55));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        jButton3.setToolTipText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 145, 55));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 160, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresTxtFocusGained

        validaciones.validarEnfoque(nombresTxt);
    }//GEN-LAST:event_nombresTxtFocusGained

    private void nombresTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(nombresTxt));
    }//GEN-LAST:event_nombresTxtFocusLost

    private void nombresTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresTxtActionPerformed

    private void nombresTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresTxtKeyPressed

    }//GEN-LAST:event_nombresTxtKeyPressed

    private void nombresTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresTxtKeyReleased

    }//GEN-LAST:event_nombresTxtKeyReleased

    private void nombresTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, nombresTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, nombresTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_nombresTxtKeyTyped

    private void telefonoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTxtFocusGained
        validaciones.validarEnfoque(telefonoTxt);
    }//GEN-LAST:event_telefonoTxtFocusGained

    private void telefonoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTxtFocusLost
        
    }//GEN-LAST:event_telefonoTxtFocusLost

    private void telefonoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTxtActionPerformed

    private void telefonoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTxtKeyPressed

    private void telefonoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTxtKeyReleased

    private void telefonoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, telefonoTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, telefonoTxt,
            constantes.CONSTANTE_VALOR_POR_DEFECTO);
    }//GEN-LAST:event_telefonoTxtKeyTyped

    private void apellidosTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidosTxtFocusGained

        validaciones.validarEnfoque(apellidosTxt);
    }//GEN-LAST:event_apellidosTxtFocusGained

    private void apellidosTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidosTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(apellidosTxt));
    }//GEN-LAST:event_apellidosTxtFocusLost

    private void apellidosTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosTxtActionPerformed

    private void apellidosTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosTxtKeyPressed

    }//GEN-LAST:event_apellidosTxtKeyPressed

    private void apellidosTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosTxtKeyReleased

    }//GEN-LAST:event_apellidosTxtKeyReleased

    private void apellidosTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, apellidosTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, apellidosTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_apellidosTxtKeyTyped

    private void direccionTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTxtFocusGained

        validaciones.validarEnfoque(direccionTxt);
    }//GEN-LAST:event_direccionTxtFocusGained

    private void direccionTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(direccionTxt));
    }//GEN-LAST:event_direccionTxtFocusLost

    private void direccionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTxtActionPerformed

    private void direccionTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyPressed

    }//GEN-LAST:event_direccionTxtKeyPressed

    private void direccionTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyReleased

    }//GEN-LAST:event_direccionTxtKeyReleased

    private void direccionTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyTyped

        
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, direccionTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_direccionTxtKeyTyped

    private void tipoDocumentoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoDocumentoComboItemStateChanged
        validarSonido(validaciones.validaCombo(tipoDocumentoCombo));
    }//GEN-LAST:event_tipoDocumentoComboItemStateChanged

    private void tipoDocumentoComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoDocumentoComboFocusLost
        validarSonido(validaciones.validaCombo(tipoDocumentoCombo));
    }//GEN-LAST:event_tipoDocumentoComboFocusLost

    private void tipoDocumentoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDocumentoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDocumentoComboActionPerformed

    private void numeroDocumentoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtFocusGained
        validaciones.validarEnfoque(numeroDocumentoTxt);
    }//GEN-LAST:event_numeroDocumentoTxtFocusGained

    private void numeroDocumentoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtFocusLost
        validarSonido(validaciones.validarCampoVacio(numeroDocumentoTxt));
    }//GEN-LAST:event_numeroDocumentoTxtFocusLost

    private void numeroDocumentoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoTxtActionPerformed

    private void numeroDocumentoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoTxtKeyPressed

    private void numeroDocumentoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoTxtKeyReleased

    private void numeroDocumentoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, numeroDocumentoTxt));
        validaciones.validarCantidadCaracteresTexto(evt, numeroDocumentoTxt,
            constantes.CONSTANTE_CARACTERES_POR_LINEA);
    }//GEN-LAST:event_numeroDocumentoTxtKeyTyped

    private void celularTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celularTxtFocusGained
        validaciones.validarEnfoque(celularTxt);
    }//GEN-LAST:event_celularTxtFocusGained

    private void celularTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celularTxtFocusLost
       
    }//GEN-LAST:event_celularTxtFocusLost

    private void celularTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularTxtActionPerformed

    private void celularTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularTxtKeyPressed

    private void celularTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_celularTxtKeyReleased

    private void celularTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, celularTxt));
        validaciones.validarCantidadCaracteresTexto(evt, celularTxt,
            constantes.CONSTANTE_VALOR_POR_DEFECTO);
    }//GEN-LAST:event_celularTxtKeyTyped

    private void estadoCivilComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estadoCivilComboItemStateChanged
        validarSonido(validaciones.validaCombo(estadoCivilCombo));
    }//GEN-LAST:event_estadoCivilComboItemStateChanged

    private void estadoCivilComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_estadoCivilComboFocusLost
        validarSonido(validaciones.validaCombo(estadoCivilCombo));
    }//GEN-LAST:event_estadoCivilComboFocusLost

    private void estadoCivilComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCivilComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoCivilComboActionPerformed

    private void ciudadComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ciudadComboItemStateChanged
        validarSonido(validaciones.validaCombo(ciudadCombo));
        validaciones.ocultarCampo(ciudadEmpleadoTxt, ciudadCombo, cualLbl);
    }//GEN-LAST:event_ciudadComboItemStateChanged

    private void ciudadComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ciudadComboFocusLost
        validarSonido(validaciones.validaCombo(ciudadCombo));
    }//GEN-LAST:event_ciudadComboFocusLost

    private void ciudadComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadComboActionPerformed

    private void ciudadEmpleadoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ciudadEmpleadoTxtFocusGained

        validaciones.validarEnfoque(ciudadEmpleadoTxt);
    }//GEN-LAST:event_ciudadEmpleadoTxtFocusGained

    private void ciudadEmpleadoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ciudadEmpleadoTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(ciudadEmpleadoTxt));
    }//GEN-LAST:event_ciudadEmpleadoTxtFocusLost

    private void ciudadEmpleadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadEmpleadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadEmpleadoTxtActionPerformed

    private void ciudadEmpleadoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ciudadEmpleadoTxtKeyPressed

    }//GEN-LAST:event_ciudadEmpleadoTxtKeyPressed

    private void ciudadEmpleadoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ciudadEmpleadoTxtKeyReleased

    }//GEN-LAST:event_ciudadEmpleadoTxtKeyReleased

    private void ciudadEmpleadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ciudadEmpleadoTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, ciudadEmpleadoTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, ciudadEmpleadoTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_ciudadEmpleadoTxtKeyTyped

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed

        try {
            empleado = new Empleado();
            FacadePersona facadePersona = new FacadePersona();
            persona = new Persona();
            persona.setNumeroDocumento(numeroDocumentoTxt.getText());
            empleado.setPersona(persona);
            
            if (validaciones.validarCamposEmpleado(nombresTxt, apellidosTxt, tipoDocumentoCombo,
                    numeroDocumentoTxt, direccionTxt, jRadioButtonFemenino, jRadioButtonMasculino,
                    fechaIngresoDate, fechaNacimientoDate, estadoCivilCombo, ciudadCombo,
                    ciudadEmpleadoTxt).equals("") && facadeEmpleado.consultarEmpleado(empleado) == null) {

                    facadeEmpleado.registrarEmpleado(mapearEmpleado());
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_REGISTRO_EXITOSO);
                
                    registrarBtn.setEnabled(false);
                    modificarBtn.setEnabled(false);
                
                    mensajeLbl.setForeground(Color.green);
                    
                    validaciones.limpiarCamposEmpleado(nombresTxt, apellidosTxt, tipoDocumentoCombo,
                                           numeroDocumentoTxt, direccionTxt, telefonoTxt,
                                           celularTxt, buttonGroupGenero, fechaIngresoDate,
                                           fechaNacimientoDate, estadoCivilCombo, ciudadCombo,
                                           ciudadEmpleadoTxt);
                    modificarBtn.setEnabled(false);
                    registrarBtn.setEnabled(false);
                    
        }else{
                 mensajeLbl.setForeground(Color.red);  
                if(validaciones.compararFechas(fechaIngresoDate.getDate(), fechaNacimientoDate.getDate()).equals("")){
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_POR_DEFECTO);
                                 
                }else{
                    mensajeLbl.setText(constantes.CONSTANTE_EMPLEADO_MENOR);
                                    
                }
        }
            

    }   catch (SQLException | ParseException ex) {
            Logger.getLogger(EmpleadoGUI.class.getName()).log(Level.SEVERE, null, ex);
            mensajeLbl.setForeground(Color.red);
            mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_ERROR_CONTROLADO);
        }
        validaciones.notificarMensajeconTimer(mensajeLbl);
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
         
        try {
           
            empleado = new Empleado();
            persona = new Persona();
            persona.setNumeroDocumento(numeroDocumentoTxt.getText());
            empleado.setPersona(persona);
            if (!validaciones.validarCampoVacio(numeroDocumentoTxt) &&
                facadeEmpleado.consultarEmpleado(empleado) != null ) {

                validaciones.mapearEmpleado(facadeEmpleado.consultarEmpleado(empleado), nombresTxt, apellidosTxt,
                                            tipoDocumentoCombo, numeroDocumentoTxt, direccionTxt, telefonoTxt,
                                            celularTxt, jRadioButtonFemenino, jRadioButtonMasculino, fechaIngresoDate,
                                            fechaNacimientoDate, estadoCivilCombo, ciudadCombo, ciudadEmpleadoTxt);
                registrarBtn.setEnabled(false);
                modificarBtn.setEnabled(true);
                mensajeLbl.setForeground(Color.green);
                mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_EMPLEADO_ENCONTRADO);
                fechaIngresoDate.setEnabled(false);
                fechaNacimientoDate.setEnabled(false);

            }else{
                if (!validaciones.validarCampoVacio(numeroDocumentoTxt)) {
                registrarBtn.setEnabled(true);
                modificarBtn.setEnabled(false);
                }
                
                if (facadeEmpleado.consultarEmpleado(empleado) == null ) {
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_EMPLEADO_NO_EXISTE);
                    mensajeLbl.setForeground(Color.red);
                    fechaIngresoDate.setEnabled(true);
                    fechaNacimientoDate.setEnabled(true);
                    
                }
                
            }

        } catch (SQLException | ParseException ex) {
            Logger.getLogger(EmpleadoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
         validaciones.notificarMensajeconTimer(mensajeLbl);
       
        
    }//GEN-LAST:event_consultarBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        try {
            
                        if (validaciones.validarCamposEmpleado(nombresTxt, apellidosTxt, tipoDocumentoCombo,
                    numeroDocumentoTxt, direccionTxt, jRadioButtonFemenino, jRadioButtonMasculino,
                    fechaIngresoDate, fechaNacimientoDate, estadoCivilCombo, ciudadCombo,
                    ciudadEmpleadoTxt).equals("")){
                        mensajeLbl.setText(facadeEmpleado.modificarEmpleado(mapearEmpleado()));
                        
                        }else{
                        
                        mensajeLbl.setText(validaciones.validarCamposEmpleado(nombresTxt, apellidosTxt, tipoDocumentoCombo,
                    numeroDocumentoTxt, direccionTxt, jRadioButtonFemenino, jRadioButtonMasculino,
                    fechaIngresoDate, fechaNacimientoDate, estadoCivilCombo, ciudadCombo,
                    ciudadEmpleadoTxt));
                        }
            
            
            validaciones.notificarMensajeconTimer(mensajeLbl);

        } catch (SQLException | ParseException ex) {
            Logger.getLogger(ProductoGUIJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        validaciones.limpiarCamposEmpleado(nombresTxt, apellidosTxt, tipoDocumentoCombo,
                                           numeroDocumentoTxt, direccionTxt, telefonoTxt,
                                           celularTxt, buttonGroupGenero, fechaIngresoDate,
                                           fechaNacimientoDate, estadoCivilCombo, ciudadCombo,
                                           ciudadEmpleadoTxt);
        modificarBtn.setEnabled(false);
        registrarBtn.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog.setDefaultLookAndFeelDecorated(true); 
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessBlackSteelSkin");
                EmpleadoGUI dialog = new EmpleadoGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
 
               
                dialog.setVisible(true);
            }
        });
    }
    
         public void validarSonido(boolean flag){
         if (flag) {
              getToolkit().beep();
             
         }else{
             
         }
     } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosTxt;
    private javax.swing.ButtonGroup buttonGroupGenero;
    private javax.swing.JTextField celularTxt;
    private javax.swing.JComboBox<String> ciudadCombo;
    private javax.swing.JTextField ciudadEmpleadoTxt;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JLabel cualLbl;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JComboBox<String> estadoCivilCombo;
    private com.toedter.calendar.JDateChooser fechaIngresoDate;
    private com.toedter.calendar.JDateChooser fechaNacimientoDate;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFemenino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mensajeLbl;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JTextField nombresTxt;
    private javax.swing.JTextField numeroDocumentoTxt;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JComboBox<String> tipoDocumentoCombo;
    // End of variables declaration//GEN-END:variables

    private Empleado mapearEmpleado() {
        
        persona.setNombres(nombresTxt.getText().trim());
        persona.setApellidos(apellidosTxt.getText().trim());
        persona.setTelefono(telefonoTxt.getText().trim());
        persona.setCelular(celularTxt.getText().trim());
        persona.setTipoDocumento(tipoDocumentoCombo.getSelectedItem().toString());
        persona.setNumeroDocumento(numeroDocumentoTxt.getText().trim());
        persona.setDireccion(direccionTxt.getText().trim());
        empleado.setPersona(persona);
        empleado.setSexo(validaciones.validarEleccionGenero(jRadioButtonFemenino,
                                                            jRadioButtonMasculino));
        empleado.setFechaIngreso(fechaIngresoDate.getDate());
        empleado.setFechaNacimiento(fechaNacimientoDate.getDate());
        empleado.setCiudad(validaciones.obtenerCiudadEmpleado(ciudadEmpleadoTxt, ciudadCombo));
        empleado.setEstadoCivil(estadoCivilCombo.getSelectedItem().toString());
        empleado.setEstado(constantes.CONSTANTE_ESTADO_POR_DEFECTO);
        
        return empleado;
        
        
    }
}
