/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ConstantesAlmacenyTaller;

import Control.TipoUsuarioDAO;
import Control.Validaciones;

import Facade.FacadeEmpleado;

import Facade.FacadeUsuario;

import Modelo.Empleado;

import Modelo.Persona;
import Modelo.Usuario;
import java.awt.Color;

import java.sql.SQLException;
import java.text.ParseException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;


import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author jose luis Rodriguez
 */
public class LoginGUI extends javax.swing.JDialog {
    
    Validaciones validaciones = new Validaciones();
    ConstantesAlmacenyTaller constantes = new ConstantesAlmacenyTaller();
    TipoUsuarioDAO tipoUsuarioDAO = new TipoUsuarioDAO();
    FacadeEmpleado facadeEmpleado = new FacadeEmpleado();
    FacadeUsuario facadeUsuario = new FacadeUsuario();
    Usuario usuario;
    Empleado empleado;
    Persona persona = new Persona();
    boolean flagModificarContrasenia;

  
    
    /**
     * Creates new form MotocicletaGUI
     */
    public LoginGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

       
        
        
        this.setTitle("Login");
        this.setLocationRelativeTo(null);


    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nombreUsuarioTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        contraseniaTxt = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mensajeLbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreUsuarioTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nombreUsuarioTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreUsuarioTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        nombreUsuarioTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreUsuarioTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreUsuarioTxtFocusLost(evt);
            }
        });
        nombreUsuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTxtActionPerformed(evt);
            }
        });
        nombreUsuarioTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreUsuarioTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreUsuarioTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreUsuarioTxtKeyTyped(evt);
            }
        });
        jPanel1.add(nombreUsuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, -1));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel21.setText("Inicio de Sesión");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel29.setText("Contraseña");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        contraseniaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contraseniaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseniaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contraseniaTxtFocusLost(evt);
            }
        });
        contraseniaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseniaTxtKeyTyped(evt);
            }
        });
        jPanel1.add(contraseniaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 280, 26));

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel22.setText("Nombre usuario");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iniciarPrincipal.png"))); // NOI18N
        jButton1.setToolTipText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 110, 60));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loginPrincipal.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 140, 130));

        mensajeLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(mensajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 260, 30));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jTabbedPane1.addTab("Login", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuarioTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreUsuarioTxtFocusGained

        validaciones.validarEnfoque(nombreUsuarioTxt);
    }//GEN-LAST:event_nombreUsuarioTxtFocusGained

    private void nombreUsuarioTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreUsuarioTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(nombreUsuarioTxt));

  
        
    }//GEN-LAST:event_nombreUsuarioTxtFocusLost

    private void nombreUsuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTxtActionPerformed

    private void nombreUsuarioTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreUsuarioTxtKeyPressed

    }//GEN-LAST:event_nombreUsuarioTxtKeyPressed

    private void nombreUsuarioTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreUsuarioTxtKeyReleased

    }//GEN-LAST:event_nombreUsuarioTxtKeyReleased

    private void nombreUsuarioTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreUsuarioTxtKeyTyped

        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, nombreUsuarioTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_nombreUsuarioTxtKeyTyped

    private void contraseniaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseniaTxtFocusLost


    }//GEN-LAST:event_contraseniaTxtFocusLost

    private void contraseniaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseniaTxtFocusGained
        
    }//GEN-LAST:event_contraseniaTxtFocusGained

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusGained

    private void contraseniaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseniaTxtKeyTyped
        validarSonido(validaciones.validarEspacioVacio(evt, contraseniaTxt));
        flagModificarContrasenia = true;
    }//GEN-LAST:event_contraseniaTxtKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        facadeUsuario = new FacadeUsuario();

        try {
            
            if (!nombreUsuarioTxt.getText().trim().equals("") &&
                !contraseniaTxt.getText().trim().equals("")) {   
                
                usuario = facadeUsuario.consultarUsuarioNombreUsuario(nombreUsuarioTxt.getText().trim());
                
                if (usuario != null && usuario.getContrasenia().trim().equals(contraseniaTxt.getText())) {
                    MenuPrincipalGUI menuPrincipalGUI = new MenuPrincipalGUI(usuario.getTipoUsuario());                    
                    dispose();
                    
                    menuPrincipalGUI.setVisible(true);
                    menuPrincipalGUI.setLocationRelativeTo(null);
                }else{
                
                    if (usuario == null) {
                       mensajeLbl.setForeground(Color.red);
                       mensajeLbl.setText("NO COINCIDE USUARIO Y CONTRASEÑA");
                    }else if(!usuario.getContrasenia().trim().equals(contraseniaTxt.getText())){
                       mensajeLbl.setForeground(Color.red);
                       mensajeLbl.setText("NO COINCIDE USUARIO Y CONTRASEÑA");                    
                    
                    }
                }
                validaciones.notificarMensajeconTimer(mensajeLbl);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog.setDefaultLookAndFeelDecorated(true); 
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessBlackSteelSkin");
                LoginGUI dialog = new LoginGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseniaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mensajeLbl;
    private javax.swing.JTextField nombreUsuarioTxt;
    // End of variables declaration//GEN-END:variables

     public void validarSonido(boolean flag){
         if (flag) {
              getToolkit().beep();
             
         }else{
             
         }
     } 


}
