/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ConstantesAlmacenyTaller;
import Control.TipoMotocicletaDAO;
import Control.Validaciones;
import Modelo.Cliente;
import Modelo.Motocicleta;
import java.awt.Color;
import javax.swing.JDialog;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author jose luis Rodriguez
 */
public class ModalMotocicletaGUI extends javax.swing.JDialog {
    Motocicleta moto = new Motocicleta();
    static Cliente cliente = new Cliente();
    Validaciones validaciones = new Validaciones();
    ConstantesAlmacenyTaller constantes = new ConstantesAlmacenyTaller();
    TipoMotocicletaDAO tipoMotocicletaDAO = new TipoMotocicletaDAO();
    /**
     * Creates new form MotocicletaGUI
     */
    public ModalMotocicletaGUI(java.awt.Frame parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        initComponents();
        this.cliente= cliente;
        cliente.setMotocicleta(moto);
        validaciones.adicionarItems(tipoMotocicletaCombo,
        tipoMotocicletaDAO.consultarTiposMotocicleta());
        
        this.setTitle("Informacion Motocicleta");
        this.setLocationRelativeTo(null);
        paisTxt.setText(constantes.CONSTANTE_PAIS_POR_DEFECTO);
        paisTxt.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        placaTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        paisTxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jRadioButtonOtro = new javax.swing.JRadioButton();
        modeloTxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        marcaCombo = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cilindrajeTxt = new javax.swing.JTextField();
        lineaTxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonGuardarMotocicleta = new javax.swing.JButton();
        tipoMotocicletaCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mensajeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        placaTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        placaTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        placaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                placaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                placaTxtFocusLost(evt);
            }
        });
        placaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaTxtActionPerformed(evt);
            }
        });
        placaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                placaTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                placaTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placaTxtKeyTyped(evt);
            }
        });
        getContentPane().add(placaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, -1));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setText("Placa");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 10));

        paisTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        paisTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        paisTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paisTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paisTxtFocusLost(evt);
            }
        });
        paisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisTxtActionPerformed(evt);
            }
        });
        paisTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paisTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paisTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paisTxtKeyTyped(evt);
            }
        });
        getContentPane().add(paisTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel23.setText("Pais");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jRadioButtonOtro.setText("Otro?");
        jRadioButtonOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOtroActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        modeloTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        modeloTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        modeloTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                modeloTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                modeloTxtFocusLost(evt);
            }
        });
        modeloTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloTxtActionPerformed(evt);
            }
        });
        modeloTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modeloTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                modeloTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modeloTxtKeyTyped(evt);
            }
        });
        getContentPane().add(modeloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 10));

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel25.setText("Modelo");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 10));

        marcaCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        marcaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "AUTECO", "KAWASAKI", "YAMAHA", "SUZUKI", "KTM", "AKT", "HONDA", "HERO", "OTRA" }));
        marcaCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                marcaComboItemStateChanged(evt);
            }
        });
        marcaCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                marcaComboFocusLost(evt);
            }
        });
        marcaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaComboActionPerformed(evt);
            }
        });
        getContentPane().add(marcaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 180, -1));

        jLabel27.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel27.setText("Marca");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("*");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 10));

        cilindrajeTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cilindrajeTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        cilindrajeTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cilindrajeTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cilindrajeTxtFocusLost(evt);
            }
        });
        cilindrajeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cilindrajeTxtActionPerformed(evt);
            }
        });
        cilindrajeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cilindrajeTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cilindrajeTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cilindrajeTxtKeyTyped(evt);
            }
        });
        getContentPane().add(cilindrajeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 180, -1));

        lineaTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lineaTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        lineaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lineaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lineaTxtFocusLost(evt);
            }
        });
        lineaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaTxtActionPerformed(evt);
            }
        });
        lineaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lineaTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lineaTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lineaTxtKeyTyped(evt);
            }
        });
        getContentPane().add(lineaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 180, -1));

        jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel29.setText("Cilindraje");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("*");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 10));

        jLabel31.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel31.setText("Linea");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("*");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, 10));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 145, 55));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motocicleta.png"))); // NOI18N
        jLabel1.setText("Motocicleta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jButtonGuardarMotocicleta.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonGuardarMotocicleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jButtonGuardarMotocicleta.setText("Guardar");
        jButtonGuardarMotocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarMotocicletaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarMotocicleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 145, 55));

        tipoMotocicletaCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tipoMotocicletaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --" }));
        tipoMotocicletaCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoMotocicletaComboItemStateChanged(evt);
            }
        });
        tipoMotocicletaCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tipoMotocicletaComboFocusLost(evt);
            }
        });
        tipoMotocicletaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoMotocicletaComboActionPerformed(evt);
            }
        });
        getContentPane().add(tipoMotocicletaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("Tipo de Motocicleta");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 10));

        mensajeLbl.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        mensajeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mensajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 350, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_placaTxtFocusGained

        validaciones.validarEnfoque(placaTxt);
    }//GEN-LAST:event_placaTxtFocusGained

    private void placaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_placaTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(placaTxt));
        if (!validaciones.validarPlaca(placaTxt.getText())) {
            validarSonido(true);
            mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_PLACA);
            mensajeLbl.setForeground(Color.red);
            validaciones.notificarMensajeconTimer(mensajeLbl);
        }
  
    }//GEN-LAST:event_placaTxtFocusLost

    private void placaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaTxtActionPerformed

    private void placaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placaTxtKeyPressed

    }//GEN-LAST:event_placaTxtKeyPressed

    private void placaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placaTxtKeyReleased

    }//GEN-LAST:event_placaTxtKeyReleased

    private void placaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placaTxtKeyTyped

        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, placaTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_placaTxtKeyTyped

    private void paisTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paisTxtFocusGained

        validaciones.validarEnfoque(paisTxt);
    }//GEN-LAST:event_paisTxtFocusGained

    private void paisTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paisTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(paisTxt));
    }//GEN-LAST:event_paisTxtFocusLost

    private void paisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisTxtActionPerformed

    private void paisTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisTxtKeyPressed

    }//GEN-LAST:event_paisTxtKeyPressed

    private void paisTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisTxtKeyReleased

    }//GEN-LAST:event_paisTxtKeyReleased

    private void paisTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, paisTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, paisTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_paisTxtKeyTyped

    private void jRadioButtonOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOtroActionPerformed
        if (jRadioButtonOtro.isSelected()) {
            paisTxt.setEnabled(true);
            paisTxt.setText(""); 
            paisTxt.setBackground(Color.white);
        }else{
            paisTxt.setEnabled(false);
            paisTxt.setText(validaciones.CONSTANTE_PAIS_POR_DEFECTO); 
        }
   
    }//GEN-LAST:event_jRadioButtonOtroActionPerformed

    private void modeloTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modeloTxtFocusGained
        validaciones.validarEnfoque(modeloTxt);
    }//GEN-LAST:event_modeloTxtFocusGained

    private void modeloTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modeloTxtFocusLost

    }//GEN-LAST:event_modeloTxtFocusLost

    private void modeloTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTxtActionPerformed

    private void modeloTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeloTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTxtKeyPressed

    private void modeloTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeloTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTxtKeyReleased

    private void modeloTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeloTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, modeloTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, modeloTxt,
            constantes.CONSTANTE_VALOR_ANIO_POR_DEFECTO);
    }//GEN-LAST:event_modeloTxtKeyTyped

    private void marcaComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_marcaComboItemStateChanged
        validarSonido(validaciones.validaCombo(marcaCombo));

    }//GEN-LAST:event_marcaComboItemStateChanged

    private void marcaComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcaComboFocusLost
        validarSonido(validaciones.validaCombo(marcaCombo));
    }//GEN-LAST:event_marcaComboFocusLost

    private void marcaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaComboActionPerformed
 
    }//GEN-LAST:event_marcaComboActionPerformed

    private void cilindrajeTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cilindrajeTxtFocusGained
        validaciones.validarEnfoque(cilindrajeTxt);
    }//GEN-LAST:event_cilindrajeTxtFocusGained

    private void cilindrajeTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cilindrajeTxtFocusLost
        validarSonido(validaciones.validarCampoVacio(cilindrajeTxt));
    }//GEN-LAST:event_cilindrajeTxtFocusLost

    private void cilindrajeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cilindrajeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cilindrajeTxtActionPerformed

    private void cilindrajeTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cilindrajeTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cilindrajeTxtKeyPressed

    private void cilindrajeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cilindrajeTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cilindrajeTxtKeyReleased

    private void cilindrajeTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cilindrajeTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, cilindrajeTxt));
        validaciones.validarCantidadCaracteresTexto(evt, cilindrajeTxt,
            constantes.CONSTANTE_VALOR_ANIO_POR_DEFECTO);
    }//GEN-LAST:event_cilindrajeTxtKeyTyped

    private void lineaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lineaTxtFocusGained

        validaciones.validarEnfoque(lineaTxt);
    }//GEN-LAST:event_lineaTxtFocusGained

    private void lineaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lineaTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(lineaTxt));
    }//GEN-LAST:event_lineaTxtFocusLost

    private void lineaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineaTxtActionPerformed

    private void lineaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lineaTxtKeyPressed

    }//GEN-LAST:event_lineaTxtKeyPressed

    private void lineaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lineaTxtKeyReleased

    }//GEN-LAST:event_lineaTxtKeyReleased

    private void lineaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lineaTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, lineaTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, lineaTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_lineaTxtKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonGuardarMotocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarMotocicletaActionPerformed
        
        if (mapeoMotocicleta()) {
            validarSonido(mapeoMotocicleta());
            mensajeLbl.setForeground(Color.red);
            mensajeLbl.setText(validaciones.CONSTANTE_CAMPO_OBLIGATORIO);
        }else{
           
            mapeoMotocicleta();
            dispose();
        }

        validaciones.notificarMensajeconTimer(mensajeLbl);
    }//GEN-LAST:event_jButtonGuardarMotocicletaActionPerformed

    private void tipoMotocicletaComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoMotocicletaComboItemStateChanged
        validarSonido(validaciones.validaCombo(tipoMotocicletaCombo));
    }//GEN-LAST:event_tipoMotocicletaComboItemStateChanged

    private void tipoMotocicletaComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoMotocicletaComboFocusLost
        validarSonido(validaciones.validaCombo(tipoMotocicletaCombo));
    }//GEN-LAST:event_tipoMotocicletaComboFocusLost

    private void tipoMotocicletaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoMotocicletaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoMotocicletaComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog.setDefaultLookAndFeelDecorated(true); 
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessBlackSteelSkin");
                ModalMotocicletaGUI dialog = new ModalMotocicletaGUI(new javax.swing.JFrame(), true, cliente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cilindrajeTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGuardarMotocicleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JRadioButton jRadioButtonOtro;
    private javax.swing.JTextField lineaTxt;
    private javax.swing.JComboBox<String> marcaCombo;
    private javax.swing.JLabel mensajeLbl;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JTextField paisTxt;
    private javax.swing.JTextField placaTxt;
    private javax.swing.JComboBox<String> tipoMotocicletaCombo;
    // End of variables declaration//GEN-END:variables

     public void validarSonido(boolean flag){
         if (flag) {
              getToolkit().beep();
             
         }else{
             
         }
     } 
     
     public boolean mapeoMotocicleta(){
         if ((!placaTxt.getText().equals("") && placaTxt.getText() !=null) &&
             (!paisTxt.getText().equals("") && paisTxt.getText() !=null) &&
             (!modeloTxt.getText().equals("") && modeloTxt.getText() !=null) &&
             (!cilindrajeTxt.getText().equals("") && cilindrajeTxt.getText() !=null)&&
             (!lineaTxt.getText().equals("") && lineaTxt.getText() !=null) &&
             (!tipoMotocicletaCombo.getSelectedItem().toString().equals(validaciones.CONSTANTE_COMBO_POR_DEFECTO) && 
               tipoMotocicletaCombo.getSelectedItem() != null) &&   
             (!marcaCombo.getSelectedItem().toString().equals(validaciones.CONSTANTE_COMBO_POR_DEFECTO) && 
               marcaCombo.getSelectedItem() != null)) {
             
                    moto.setPlaca(placaTxt.getText());
                    moto.setPaisMatricula(paisTxt.getText());
                    moto.setModelo(modeloTxt.getText());
                    moto.setCilindraje(cilindrajeTxt.getText());
                    moto.setLinea(lineaTxt.getText());
                    moto.setMarca(marcaCombo.getSelectedItem().toString());
                    moto.setTipoMotocicleta(tipoMotocicletaCombo.getSelectedItem().toString());
                    return false;
             
         }
         return true;
     
     }

}
