/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ConstantesAlmacenyTaller;
import Control.TipoMotocicletaDAO;
import Control.Validaciones;
import Facade.FacadeCliente;
import Facade.FacadeMotociccleta;
import Modelo.Cliente;
import Modelo.Empleado;
import Modelo.Motocicleta;
import Modelo.Persona;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author jose luis Rodriguez
 */
public class MotocicletaGUI extends javax.swing.JDialog {
    Motocicleta moto = new Motocicleta();
    static Cliente cliente = new Cliente();
    Validaciones validaciones = new Validaciones();
    ConstantesAlmacenyTaller constantes = new ConstantesAlmacenyTaller();
    TipoMotocicletaDAO tipoMotocicletaDAO = new TipoMotocicletaDAO();
    Persona persona = new Persona();
    FacadeCliente facadeCliente = new FacadeCliente();
    FacadeMotociccleta facadeMotocicleta = new FacadeMotociccleta();
    int posicionMotocicleta = 0;
    List<Motocicleta> listaMotocicleta = new ArrayList<Motocicleta>();
    /**
     * Creates new form MotocicletaGUI
     */
    public MotocicletaGUI(java.awt.Frame parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        initComponents();
        this.cliente= cliente;
        cliente.setMotocicleta(moto);
        validaciones.adicionarItems(tipoMotocicletaCombo,
        tipoMotocicletaDAO.consultarTiposMotocicleta());
        registrarBtn.setEnabled(false);
        this.setTitle("Gestion Motocicleta");
        this.setLocationRelativeTo(null);
        paisTxt.setText(constantes.CONSTANTE_PAIS_POR_DEFECTO);
        paisTxt.setEnabled(false);
        modificarBtn.setEnabled(false);
        anteriorBtn.setVisible(false);
        siguienteBtn.setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tipoMotocicletaCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        modeloTxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        paisTxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        placaTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cilindrajeTxt = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lineaTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        marcaCombo = new javax.swing.JComboBox<>();
        registrarBtn = new javax.swing.JButton();
        jRadioButtonOtro = new javax.swing.JRadioButton();
        numeroDocumentoTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nombresTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        consultarBtn = new javax.swing.JButton();
        siguienteBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        anteriorBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mensajeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoMotocicletaCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tipoMotocicletaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --" }));
        tipoMotocicletaCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoMotocicletaComboItemStateChanged(evt);
            }
        });
        tipoMotocicletaCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tipoMotocicletaComboFocusLost(evt);
            }
        });
        tipoMotocicletaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoMotocicletaComboActionPerformed(evt);
            }
        });
        jPanel1.add(tipoMotocicletaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("Tipo de Motocicleta");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, 10));

        modeloTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        modeloTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        modeloTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                modeloTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                modeloTxtFocusLost(evt);
            }
        });
        modeloTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloTxtActionPerformed(evt);
            }
        });
        modeloTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modeloTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                modeloTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modeloTxtKeyTyped(evt);
            }
        });
        jPanel1.add(modeloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, -1));

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel25.setText("Modelo");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 10));

        paisTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        paisTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        paisTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paisTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paisTxtFocusLost(evt);
            }
        });
        paisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisTxtActionPerformed(evt);
            }
        });
        paisTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paisTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paisTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paisTxtKeyTyped(evt);
            }
        });
        jPanel1.add(paisTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel23.setText("Pais");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 10));

        placaTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        placaTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        placaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                placaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                placaTxtFocusLost(evt);
            }
        });
        placaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaTxtActionPerformed(evt);
            }
        });
        placaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                placaTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                placaTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placaTxtKeyTyped(evt);
            }
        });
        jPanel1.add(placaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setText("Placa");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 10));

        jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel29.setText("Cilindraje");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("*");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 10));

        cilindrajeTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cilindrajeTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        cilindrajeTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cilindrajeTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cilindrajeTxtFocusLost(evt);
            }
        });
        cilindrajeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cilindrajeTxtActionPerformed(evt);
            }
        });
        cilindrajeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cilindrajeTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cilindrajeTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cilindrajeTxtKeyTyped(evt);
            }
        });
        jPanel1.add(cilindrajeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 180, -1));

        jLabel31.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel31.setText("Linea");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("*");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, 10));

        lineaTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lineaTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        lineaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lineaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lineaTxtFocusLost(evt);
            }
        });
        lineaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaTxtActionPerformed(evt);
            }
        });
        lineaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lineaTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lineaTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lineaTxtKeyTyped(evt);
            }
        });
        jPanel1.add(lineaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 180, -1));

        jLabel27.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel27.setText("Marca");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("*");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 10));

        marcaCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        marcaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "AUTECO", "KAWASAKI", "YAMAHA", "SUZUKI", "KTM", "AKT", "HONDA", "HERO", "OTRA" }));
        marcaCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                marcaComboItemStateChanged(evt);
            }
        });
        marcaCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                marcaComboFocusLost(evt);
            }
        });
        marcaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaComboActionPerformed(evt);
            }
        });
        jPanel1.add(marcaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 180, -1));

        registrarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        registrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        registrarBtn.setToolTipText("GUARDAR");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 145, 55));

        jRadioButtonOtro.setText("Otro?");
        jRadioButtonOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOtroActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        numeroDocumentoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        numeroDocumentoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        numeroDocumentoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroDocumentoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroDocumentoTxtFocusLost(evt);
            }
        });
        numeroDocumentoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDocumentoTxtActionPerformed(evt);
            }
        });
        numeroDocumentoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroDocumentoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroDocumentoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDocumentoTxtKeyTyped(evt);
            }
        });
        jPanel1.add(numeroDocumentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("Documento Propietario");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        nombresTxt.setEditable(false);
        nombresTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nombresTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        nombresTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresTxtFocusLost(evt);
            }
        });
        nombresTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresTxtActionPerformed(evt);
            }
        });
        nombresTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombresTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombresTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresTxtKeyTyped(evt);
            }
        });
        jPanel1.add(nombresTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Nombres");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        consultarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        consultarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        consultarBtn.setToolTipText("CONSULTAR");
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(consultarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 145, 55));

        siguienteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/siguiente.png"))); // NOI18N
        siguienteBtn.setToolTipText("SIGUIENTE");
        siguienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(siguienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        modificarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        modificarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        modificarBtn.setToolTipText("MODIFICAR");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 145, 55));

        anteriorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/anterior.png"))); // NOI18N
        anteriorBtn.setToolTipText("ANTERIOR");
        anteriorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorBtnActionPerformed(evt);
            }
        });
        jPanel1.add(anteriorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        jButton3.setToolTipText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 145, 55));

        jTabbedPane1.addTab("Datos de la Motocicleta", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 350));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motocicleta.png"))); // NOI18N
        jLabel1.setText("Motocicleta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        mensajeLbl.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        mensajeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mensajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 350, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_placaTxtFocusGained

        validaciones.validarEnfoque(placaTxt);
    }//GEN-LAST:event_placaTxtFocusGained

    private void placaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_placaTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(placaTxt));
        if (!validaciones.validarPlaca(placaTxt.getText())) {
            validarSonido(true);
            mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_PLACA);
            mensajeLbl.setForeground(Color.red);
            validaciones.notificarMensajeconTimer(mensajeLbl);
        }
  
        
    }//GEN-LAST:event_placaTxtFocusLost

    private void placaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaTxtActionPerformed

    private void placaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placaTxtKeyPressed

    }//GEN-LAST:event_placaTxtKeyPressed

    private void placaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placaTxtKeyReleased

    }//GEN-LAST:event_placaTxtKeyReleased

    private void placaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placaTxtKeyTyped

        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, placaTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_placaTxtKeyTyped

    private void paisTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paisTxtFocusGained

        validaciones.validarEnfoque(paisTxt);
    }//GEN-LAST:event_paisTxtFocusGained

    private void paisTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paisTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(paisTxt));
    }//GEN-LAST:event_paisTxtFocusLost

    private void paisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisTxtActionPerformed

    private void paisTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisTxtKeyPressed

    }//GEN-LAST:event_paisTxtKeyPressed

    private void paisTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisTxtKeyReleased

    }//GEN-LAST:event_paisTxtKeyReleased

    private void paisTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, paisTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, paisTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_paisTxtKeyTyped

    private void jRadioButtonOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOtroActionPerformed
        if (jRadioButtonOtro.isSelected()) {
            paisTxt.setEnabled(true);
            paisTxt.setText(""); 
            paisTxt.setBackground(Color.white);
        }else{
            paisTxt.setEnabled(false);
            paisTxt.setText(validaciones.CONSTANTE_PAIS_POR_DEFECTO); 
        }
   
    }//GEN-LAST:event_jRadioButtonOtroActionPerformed

    private void modeloTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modeloTxtFocusGained
        validaciones.validarEnfoque(modeloTxt);
    }//GEN-LAST:event_modeloTxtFocusGained

    private void modeloTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modeloTxtFocusLost

    }//GEN-LAST:event_modeloTxtFocusLost

    private void modeloTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTxtActionPerformed

    private void modeloTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeloTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTxtKeyPressed

    private void modeloTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeloTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTxtKeyReleased

    private void modeloTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeloTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, modeloTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, modeloTxt,
            constantes.CONSTANTE_VALOR_ANIO_POR_DEFECTO);
    }//GEN-LAST:event_modeloTxtKeyTyped

    private void marcaComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_marcaComboItemStateChanged
        validarSonido(validaciones.validaCombo(marcaCombo));

    }//GEN-LAST:event_marcaComboItemStateChanged

    private void marcaComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcaComboFocusLost
        validarSonido(validaciones.validaCombo(marcaCombo));
    }//GEN-LAST:event_marcaComboFocusLost

    private void marcaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaComboActionPerformed
 
    }//GEN-LAST:event_marcaComboActionPerformed

    private void cilindrajeTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cilindrajeTxtFocusGained
        validaciones.validarEnfoque(cilindrajeTxt);
    }//GEN-LAST:event_cilindrajeTxtFocusGained

    private void cilindrajeTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cilindrajeTxtFocusLost
        validarSonido(validaciones.validarCampoVacio(cilindrajeTxt));
    }//GEN-LAST:event_cilindrajeTxtFocusLost

    private void cilindrajeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cilindrajeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cilindrajeTxtActionPerformed

    private void cilindrajeTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cilindrajeTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cilindrajeTxtKeyPressed

    private void cilindrajeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cilindrajeTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cilindrajeTxtKeyReleased

    private void cilindrajeTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cilindrajeTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, cilindrajeTxt));
        validaciones.validarCantidadCaracteresTexto(evt, cilindrajeTxt,
            constantes.CONSTANTE_CARACTERES_POR_LINEA);
    }//GEN-LAST:event_cilindrajeTxtKeyTyped

    private void lineaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lineaTxtFocusGained

        validaciones.validarEnfoque(lineaTxt);
    }//GEN-LAST:event_lineaTxtFocusGained

    private void lineaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lineaTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(lineaTxt));
    }//GEN-LAST:event_lineaTxtFocusLost

    private void lineaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineaTxtActionPerformed

    private void lineaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lineaTxtKeyPressed

    }//GEN-LAST:event_lineaTxtKeyPressed

    private void lineaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lineaTxtKeyReleased

    }//GEN-LAST:event_lineaTxtKeyReleased

    private void lineaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lineaTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, lineaTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, lineaTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_lineaTxtKeyTyped

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        
        
        try {
            cliente = new Cliente();
            persona.setNumeroDocumento(numeroDocumentoTxt.getText());
            cliente.setPersona(persona);
            moto.setPlaca(placaTxt.getText());
            if (validaciones.validarCamposMotocicleta(placaTxt, cilindrajeTxt,
                paisTxt, lineaTxt, modeloTxt, marcaCombo,
                tipoMotocicletaCombo).equals("") &&
                facadeCliente.consultarCliente(cliente) != null &&
                facadeMotocicleta.consultarMotocicleta(moto) == null) {
                cliente = facadeCliente.consultarCliente(cliente);
                facadeMotocicleta.registrarMotocicleta(mapeoMotocicleta(cliente));
                    
        }else{
                if (!validaciones.validarCamposMotocicleta(placaTxt, cilindrajeTxt,
                paisTxt, lineaTxt, modeloTxt, marcaCombo,
                tipoMotocicletaCombo).equals("")) {
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_POR_DEFECTO);
                }else if(facadeCliente.consultarCliente(cliente) == null){
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_NO_EXISTE_REGISTRO);
                }else if(facadeMotocicleta.consultarMotocicleta(moto) != null){
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_EXISTE_PLACA);
                }
                
                    
    }
            validaciones.notificarMensajeconTimer(mensajeLbl);

    }   catch (SQLException | ParseException ex) {
            Logger.getLogger(EmpleadoGUI.class.getName()).log(Level.SEVERE, null, ex);
        } 
          
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void tipoMotocicletaComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoMotocicletaComboItemStateChanged
        validarSonido(validaciones.validaCombo(tipoMotocicletaCombo));
    }//GEN-LAST:event_tipoMotocicletaComboItemStateChanged

    private void tipoMotocicletaComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoMotocicletaComboFocusLost
        validarSonido(validaciones.validaCombo(tipoMotocicletaCombo));
    }//GEN-LAST:event_tipoMotocicletaComboFocusLost

    private void tipoMotocicletaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoMotocicletaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoMotocicletaComboActionPerformed

    private void numeroDocumentoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtFocusGained
        validaciones.validarEnfoque(numeroDocumentoTxt);
    }//GEN-LAST:event_numeroDocumentoTxtFocusGained

    private void numeroDocumentoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtFocusLost
        validarSonido(validaciones.validarCampoVacio(numeroDocumentoTxt));
    }//GEN-LAST:event_numeroDocumentoTxtFocusLost

    private void numeroDocumentoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoTxtActionPerformed

    private void numeroDocumentoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoTxtKeyPressed

    private void numeroDocumentoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoTxtKeyReleased

    private void numeroDocumentoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, numeroDocumentoTxt));
        validaciones.validarCantidadCaracteresTexto(evt, numeroDocumentoTxt,
            constantes.CONSTANTE_CARACTERES_POR_LINEA);
    }//GEN-LAST:event_numeroDocumentoTxtKeyTyped

    private void nombresTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresTxtFocusGained

       
    }//GEN-LAST:event_nombresTxtFocusGained

    private void nombresTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresTxtFocusLost

       
    }//GEN-LAST:event_nombresTxtFocusLost

    private void nombresTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresTxtActionPerformed

    private void nombresTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresTxtKeyPressed

    }//GEN-LAST:event_nombresTxtKeyPressed

    private void nombresTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresTxtKeyReleased

    }//GEN-LAST:event_nombresTxtKeyReleased

    private void nombresTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, nombresTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, nombresTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_nombresTxtKeyTyped

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed

        try {

            cliente = new Cliente();
            persona = new Persona();
            persona.setNumeroDocumento(numeroDocumentoTxt.getText());
            cliente.setPersona(persona);
            if (!validaciones.validarCampoVacio(numeroDocumentoTxt) &&
                facadeCliente.consultarCliente(cliente) != null ) {
                
                cliente = facadeCliente.consultarCliente(cliente);
                nombresTxt.setText(cliente.getPersona().getNombres().trim()+
                        " "+cliente.getPersona().getApellidos().trim());
                System.out.println("nombres"+cliente.getPersona().getNombres().trim()+
                        " "+cliente.getPersona().getApellidos().trim());
                
                    listaMotocicleta = facadeMotocicleta.consultarMotocicletasPorCliente(
                    numeroDocumentoTxt.getText());
                if(listaMotocicleta != null){
                    posicionMotocicleta = 0;
                    validaciones.mapearMotocicleta(listaMotocicleta.get(posicionMotocicleta), placaTxt, paisTxt, modeloTxt, cilindrajeTxt,
                    lineaTxt, tipoMotocicletaCombo, marcaCombo, jRadioButtonOtro);
                    moto.setCodMotocicleta(listaMotocicleta.get(posicionMotocicleta).getCodMotocicleta());
                    registrarBtn.setEnabled(false);
                    modificarBtn.setEnabled(true);
                    if(listaMotocicleta.size() > 1){
                        anteriorBtn.setVisible(true);
                        siguienteBtn.setVisible(true);
                    }else{
                        anteriorBtn.setVisible(false);
                        siguienteBtn.setVisible(false);                    
                    }
                }else{
                    registrarBtn.setEnabled(true);
                }
                

            }else{
                if (!validaciones.validarCampoVacio(numeroDocumentoTxt)) {
                    registrarBtn.setEnabled(false);
                    //modificarBtn.setEnabled(false);

                }

            }

        } catch (SQLException | ParseException ex) {
            Logger.getLogger(EmpleadoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultarBtnActionPerformed

    private void siguienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBtnActionPerformed
        if (!listaMotocicleta.isEmpty() && listaMotocicleta.size() > posicionMotocicleta+1) {

            posicionMotocicleta++;
            validaciones.mapearMotocicleta(listaMotocicleta.get(posicionMotocicleta), placaTxt, paisTxt, modeloTxt, cilindrajeTxt,
                    lineaTxt, tipoMotocicletaCombo, marcaCombo, jRadioButtonOtro);
            if (!paisTxt.getText().equals(constantes.CONSTANTE_PAIS_POR_DEFECTO)) {
                jRadioButtonOtro.setSelected(true);
            }else{
                jRadioButtonOtro.setSelected(false);
                paisTxt.setEnabled(false);
            }
        }
    }//GEN-LAST:event_siguienteBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        try {

            if (validaciones.validarCamposMotocicleta(placaTxt, cilindrajeTxt, paisTxt, lineaTxt,
                modeloTxt, marcaCombo, tipoMotocicletaCombo).equals("")){
            mensajeLbl.setText(facadeMotocicleta.modificarMotocicleta(mapeoMotocicleta(cliente)));

        }else{

            mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_POR_DEFECTO);
        }

        validaciones.notificarMensajeconTimer(mensajeLbl);

        } catch (SQLException | ParseException ex) {
            Logger.getLogger(ProductoGUIJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void anteriorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorBtnActionPerformed
        if (!listaMotocicleta.isEmpty() && posicionMotocicleta > 0) {

            posicionMotocicleta--;
            validaciones.mapearMotocicleta(listaMotocicleta.get(posicionMotocicleta), placaTxt, paisTxt, modeloTxt, cilindrajeTxt,
                    lineaTxt, tipoMotocicletaCombo, marcaCombo, jRadioButtonOtro);
            if (!paisTxt.getText().equals(constantes.CONSTANTE_PAIS_POR_DEFECTO)) {
                jRadioButtonOtro.setSelected(true);
            }else{
                jRadioButtonOtro.setSelected(false);
                paisTxt.setEnabled(false);
            }
        }
    }//GEN-LAST:event_anteriorBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        validaciones.limpiarCamposMotocicleta(placaTxt, paisTxt, modeloTxt, cilindrajeTxt,
                                              lineaTxt, tipoMotocicletaCombo, marcaCombo,
                                              jRadioButtonOtro, numeroDocumentoTxt, nombresTxt,
                                              anteriorBtn, siguienteBtn);
        modificarBtn.setEnabled(false);
        registrarBtn.setEnabled(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog.setDefaultLookAndFeelDecorated(true); 
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessBlackSteelSkin");
                MotocicletaGUI dialog = new MotocicletaGUI(new javax.swing.JFrame(), true, cliente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorBtn;
    private javax.swing.JTextField cilindrajeTxt;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonOtro;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lineaTxt;
    private javax.swing.JComboBox<String> marcaCombo;
    private javax.swing.JLabel mensajeLbl;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JTextField nombresTxt;
    private javax.swing.JTextField numeroDocumentoTxt;
    private javax.swing.JTextField paisTxt;
    private javax.swing.JTextField placaTxt;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JButton siguienteBtn;
    private javax.swing.JComboBox<String> tipoMotocicletaCombo;
    // End of variables declaration//GEN-END:variables

     public void validarSonido(boolean flag){
         if (flag) {
              getToolkit().beep();
             
         }else{
             
         }
     } 
     
     public Motocicleta mapeoMotocicleta(Cliente cliente){
         if ((!placaTxt.getText().equals("") && placaTxt.getText() !=null) &&
             (!paisTxt.getText().equals("") && paisTxt.getText() !=null) &&
             (!modeloTxt.getText().equals("") && modeloTxt.getText() !=null) &&
             (!cilindrajeTxt.getText().equals("") && cilindrajeTxt.getText() !=null)&&
             (!lineaTxt.getText().equals("") && lineaTxt.getText() !=null) &&
             (!tipoMotocicletaCombo.getSelectedItem().toString().equals("") && 
               tipoMotocicletaCombo.getSelectedItem() !=null) &&   
             (!marcaCombo.getSelectedItem().toString().equals("") && 
               marcaCombo.getSelectedItem() !=null)) {
                    
                    moto.setCodCliente(cliente.getCodCliente());
                    moto.setPlaca(placaTxt.getText());
                    moto.setPaisMatricula(paisTxt.getText());
                    moto.setModelo(modeloTxt.getText());
                    moto.setCilindraje(cilindrajeTxt.getText());
                    moto.setLinea(lineaTxt.getText());
                    moto.setMarca(marcaCombo.getSelectedItem().toString());
                    moto.setTipoMotocicleta(tipoMotocicletaCombo.getSelectedItem().toString());
                    return moto;
             
         }
         return new Motocicleta();
     
     }

}
