/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ConstantesAlmacenyTaller;
import Control.DetalleAjusteDAO;
import Control.DetallePagoDAO;
import Control.PagoEmpleadoDAO;
import Control.ProductoDAO;


import Control.Validaciones;


import Facade.FacadeEmpleado;



import Control.TipoServicioDAO;
import Facade.FacadePagoEmpleado;
import Modelo.PagoEmpleado;


import Modelo.Empleado;
import Modelo.ParametrosFactura;

import Modelo.Persona;



import Modelo.DetallePago;
import Modelo.ParametrosPagoEmpleado;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;

import java.util.ArrayList;
import java.util.List;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JTable;

import javax.swing.table.DefaultTableModel;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author jose luis Rodriguez
 */
public class NominaGUI extends javax.swing.JDialog {
    
    Validaciones validaciones = new Validaciones();
    ConstantesAlmacenyTaller constantes = new ConstantesAlmacenyTaller();
    FacadeEmpleado facadeEmpleado = new FacadeEmpleado();
    Empleado empleado;
    Persona persona = new Persona();
    List<ParametrosPagoEmpleado> listaParametrosPagoEmpleado;
    
    String[] columnasTablaServiciosSeleccionados = {"SERVICIO","VLR SERVICIO","DESCUENTO","DESCRIPCION"};
    String[] columnasTablaPagoServicios = {"SERVICIO","DESCRIPCION","VLR SERVICIO","DSCTO SERVICIO","FECHA SERVICIO"};
    
    DefaultTableModel modeloTablaServiciosSeleccionados = new DefaultTableModel();
    DefaultTableModel modeloTablaServiciosPagar = new DefaultTableModel();
    ProductoDAO productoDAO;
    
    double cantidadServicioSeleccionado;
    double valorServicioSeleccionado;
    double acumulaTotales = 0;
    double descuento = 0;
    List<Double> listadoTotalesPago = new ArrayList<>();
    String tipoServicioSeleccionado;
    PagoEmpleado pagoEmpleado = new PagoEmpleado();
    FacadePagoEmpleado facadePagoEmpleado = new FacadePagoEmpleado();
    DetallePagoDAO detallePagoDAO = new DetallePagoDAO();
    TipoServicioDAO tipoServicioDAO = new TipoServicioDAO();
     PagoEmpleadoDAO pagoEmpleadoDAO = new PagoEmpleadoDAO();
    //int codigoVentaParametroFactura;
    

      
    /**
     * Creates new form MotocicletaGUI
     */
    public NominaGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        pagarNominaBtn.setVisible(false);
        registrarBtn.setEnabled(true);
        this.setTitle("Gestion Pago Servicios");
        this.setLocationRelativeTo(null);
        
       
        modeloTablaServiciosSeleccionados.setColumnIdentifiers(columnasTablaServiciosSeleccionados);
        
        serviciosSeleccionadosTabla.setModel(modeloTablaServiciosSeleccionados);
        modeloTablaServiciosPagar.setColumnIdentifiers(columnasTablaPagoServicios);
        serviciosPagarTabla.setModel(modeloTablaServiciosPagar);
        registrarBtn.setEnabled(false);
        validaciones.adicionarItems(tipoServicioCombo,
        tipoServicioDAO.consultarTiposServicio());

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        numeroDocumentoEmpleadoTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nombresEmpleadoTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fechaPagoDate = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        valorDescuentoEmpleadoTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tipoServicioCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        descripcionServicioSeleccionadoTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        descuentoServicioSeleccionadoTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        valorServicioSeleccionadoTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviciosSeleccionadosTabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        totalParcialLbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fechaFinDate = new com.toedter.calendar.JDateChooser();
        fechaInicioDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        consultarServiciosPagarBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        serviciosPagarTabla = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        numeroDocumentoEmpleadoPagoTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        nombreEmpleadoLbl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        totalPagoLbl = new javax.swing.JLabel();
        subTotalPagoLbl = new javax.swing.JLabel();
        descuentosNominaLbl = new javax.swing.JLabel();
        descuentoTallerLbl = new javax.swing.JLabel();
        pagarNominaBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        registrarBtn = new javax.swing.JButton();
        consultarBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        mensajeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 10));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setText("Fecha de Servicio");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 10));

        numeroDocumentoEmpleadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        numeroDocumentoEmpleadoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        numeroDocumentoEmpleadoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroDocumentoEmpleadoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroDocumentoEmpleadoTxtFocusLost(evt);
            }
        });
        numeroDocumentoEmpleadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDocumentoEmpleadoTxtActionPerformed(evt);
            }
        });
        numeroDocumentoEmpleadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroDocumentoEmpleadoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroDocumentoEmpleadoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDocumentoEmpleadoTxtKeyTyped(evt);
            }
        });
        jPanel1.add(numeroDocumentoEmpleadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("Documento Empleado");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        nombresEmpleadoTxt.setEditable(false);
        nombresEmpleadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nombresEmpleadoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        nombresEmpleadoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresEmpleadoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresEmpleadoTxtFocusLost(evt);
            }
        });
        nombresEmpleadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresEmpleadoTxtActionPerformed(evt);
            }
        });
        nombresEmpleadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombresEmpleadoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombresEmpleadoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresEmpleadoTxtKeyTyped(evt);
            }
        });
        jPanel1.add(nombresEmpleadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Nombres Empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        fechaPagoDate.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(fechaPagoDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 26));

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel18.setText("Valor Descuento Empleado");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        valorDescuentoEmpleadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        valorDescuentoEmpleadoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorDescuentoEmpleadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorDescuentoEmpleadoTxtActionPerformed(evt);
            }
        });
        valorDescuentoEmpleadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorDescuentoEmpleadoTxtKeyTyped(evt);
            }
        });
        jPanel1.add(valorDescuentoEmpleadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 200, 26));

        jTabbedPane1.addTab("Datos del Empleado", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoServicioCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tipoServicioCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --" }));
        tipoServicioCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoServicioComboItemStateChanged(evt);
            }
        });
        tipoServicioCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tipoServicioComboFocusLost(evt);
            }
        });
        tipoServicioCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoServicioComboActionPerformed(evt);
            }
        });
        jPanel2.add(tipoServicioCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("Tipo de Servicio");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("*");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 10));

        descripcionServicioSeleccionadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        descripcionServicioSeleccionadoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        descripcionServicioSeleccionadoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descripcionServicioSeleccionadoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descripcionServicioSeleccionadoTxtFocusLost(evt);
            }
        });
        descripcionServicioSeleccionadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionServicioSeleccionadoTxtActionPerformed(evt);
            }
        });
        descripcionServicioSeleccionadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descripcionServicioSeleccionadoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripcionServicioSeleccionadoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descripcionServicioSeleccionadoTxtKeyTyped(evt);
            }
        });
        jPanel2.add(descripcionServicioSeleccionadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel14.setText("Descripcion");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        descuentoServicioSeleccionadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        descuentoServicioSeleccionadoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        descuentoServicioSeleccionadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descuentoServicioSeleccionadoTxtActionPerformed(evt);
            }
        });
        descuentoServicioSeleccionadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descuentoServicioSeleccionadoTxtKeyTyped(evt);
            }
        });
        jPanel2.add(descuentoServicioSeleccionadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, 26));

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel17.setText("Descuento");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("%");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 10, 20));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel15.setText("Valor Servicio ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, 10));

        valorServicioSeleccionadoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        valorServicioSeleccionadoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorServicioSeleccionadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorServicioSeleccionadoTxtActionPerformed(evt);
            }
        });
        valorServicioSeleccionadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorServicioSeleccionadoTxtKeyTyped(evt);
            }
        });
        jPanel2.add(valorServicioSeleccionadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 170, 26));

        serviciosSeleccionadosTabla.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        serviciosSeleccionadosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(serviciosSeleccionadosTabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 110));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrarRegistro.png"))); // NOI18N
        jButton1.setToolTipText("ELIMINAR REGISTRO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        totalParcialLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel2.add(totalParcialLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 140, 30));

        jTabbedPane1.addTab("Datos Servicios", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechaFinDate.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel4.add(fechaFinDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, 26));

        fechaInicioDate.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel4.add(fechaInicioDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 26));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel11.setText("Total Pago");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel12.setText("Facha Inicial");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        consultarServiciosPagarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda.png"))); // NOI18N
        consultarServiciosPagarBtn.setToolTipText("CONSULTAR");
        consultarServiciosPagarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarServiciosPagarBtnActionPerformed(evt);
            }
        });
        jPanel4.add(consultarServiciosPagarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 70, 60));

        serviciosPagarTabla.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        serviciosPagarTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(serviciosPagarTabla);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 500, 110));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel13.setText("Facha Final");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        numeroDocumentoEmpleadoPagoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        numeroDocumentoEmpleadoPagoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        numeroDocumentoEmpleadoPagoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroDocumentoEmpleadoPagoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroDocumentoEmpleadoPagoTxtFocusLost(evt);
            }
        });
        numeroDocumentoEmpleadoPagoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDocumentoEmpleadoPagoTxtActionPerformed(evt);
            }
        });
        numeroDocumentoEmpleadoPagoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroDocumentoEmpleadoPagoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroDocumentoEmpleadoPagoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDocumentoEmpleadoPagoTxtKeyTyped(evt);
            }
        });
        jPanel4.add(numeroDocumentoEmpleadoPagoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel19.setText("Documento Empleado");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("*");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, 10));

        nombreEmpleadoLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nombreEmpleadoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(nombreEmpleadoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, 26));

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel20.setText("Lista Servicios Prestados");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel22.setText("Sub Total");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel23.setText("Descuentos de Nomina");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel28.setText("Descuento de Taller");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        totalPagoLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel4.add(totalPagoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 120, 26));

        subTotalPagoLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel4.add(subTotalPagoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 120, 26));

        descuentosNominaLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel4.add(descuentosNominaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 120, 26));

        descuentoTallerLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel4.add(descuentoTallerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 120, 26));

        pagarNominaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pagarNomina.png"))); // NOI18N
        pagarNominaBtn.setToolTipText("PAGAR SUELDO");
        pagarNominaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarNominaBtnActionPerformed(evt);
            }
        });
        jPanel4.add(pagarNominaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 70, 60));

        jTabbedPane1.addTab("Pago Empleado", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 500));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pagoEmpleado.png"))); // NOI18N
        jLabel1.setText("Nomina");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 270, 100));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        registrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        registrarBtn.setToolTipText("GUARDAR");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });
        jPanel3.add(registrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 145, 55));

        consultarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        consultarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        consultarBtn.setToolTipText("CONSULTAR");
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });
        jPanel3.add(consultarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 145, 60));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        jButton3.setToolTipText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 145, 55));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 160, 300));

        mensajeLbl.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        mensajeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mensajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 410, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        
       
        try {
            persona = new Persona();
            
            empleado = new Empleado();
            if (!validaciones.validarCampoVacio(numeroDocumentoEmpleadoTxt)) {
             persona.setNumeroDocumento(numeroDocumentoEmpleadoTxt.getText());
            
            }
            
            
            empleado.setPersona(persona);
           
            if (validaciones.validarCamposAjuste(numeroDocumentoEmpleadoTxt,
                fechaPagoDate, serviciosSeleccionadosTabla, tipoServicioCombo).equals("") &&
                facadeEmpleado.consultarEmpleado(empleado) != null) {
                
                
                empleado = facadeEmpleado.consultarEmpleado(empleado);
                int codigoPago = facadePagoEmpleado.registrarPagoEmpleado(mapeoPagoEmpleado(pagoEmpleado));
                registrarDetallePago(serviciosSeleccionadosTabla,codigoPago);
                mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_REGISTRO_EXITOSO);
                registrarBtn.setEnabled(false);
                limpiarCampos();
                //ComprobanteGUI comprobanteGUI = new ComprobanteGUI(null, true, mapearParametrosFactura());
                
                //comprobanteGUI.setVisible(true);
             
        }else{
                if (!validaciones.validarCamposAjuste(numeroDocumentoEmpleadoTxt,
                    fechaPagoDate, serviciosSeleccionadosTabla, tipoServicioCombo).equals("")) {
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_POR_DEFECTO);
                }else if(facadeEmpleado.consultarEmpleado(empleado) == null){
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_NO_EXISTE_REGISTRO);
                }
                mensajeLbl.setForeground(Color.red);
                    
    }
            validaciones.notificarMensajeconTimer(mensajeLbl);

    }   catch (SQLException | ParseException ex) {
            Logger.getLogger(EmpleadoGUI.class.getName()).log(Level.SEVERE, null, ex);
            mensajeLbl.setForeground(Color.red);
            mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_ERROR_CONTROLADO);
        }
        
          validaciones.notificarMensajeconTimer(mensajeLbl);
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void numeroDocumentoEmpleadoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtFocusGained
        validaciones.validarEnfoque(numeroDocumentoEmpleadoTxt);
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtFocusGained

    private void numeroDocumentoEmpleadoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtFocusLost
        validarSonido(validaciones.validarCampoVacio(numeroDocumentoEmpleadoTxt));
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtFocusLost

    private void numeroDocumentoEmpleadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtActionPerformed

    private void numeroDocumentoEmpleadoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtKeyPressed

    private void numeroDocumentoEmpleadoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtKeyReleased

    private void numeroDocumentoEmpleadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, numeroDocumentoEmpleadoTxt));
        validaciones.validarCantidadCaracteresTexto(evt, numeroDocumentoEmpleadoTxt,
            constantes.CONSTANTE_CARACTERES_POR_LINEA);
    }//GEN-LAST:event_numeroDocumentoEmpleadoTxtKeyTyped

    private void nombresEmpleadoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtFocusGained

       
    }//GEN-LAST:event_nombresEmpleadoTxtFocusGained

    private void nombresEmpleadoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtFocusLost

       
    }//GEN-LAST:event_nombresEmpleadoTxtFocusLost

    private void nombresEmpleadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresEmpleadoTxtActionPerformed

    private void nombresEmpleadoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtKeyPressed

    }//GEN-LAST:event_nombresEmpleadoTxtKeyPressed

    private void nombresEmpleadoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtKeyReleased

    }//GEN-LAST:event_nombresEmpleadoTxtKeyReleased

    private void nombresEmpleadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresEmpleadoTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, nombresEmpleadoTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, nombresEmpleadoTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_nombresEmpleadoTxtKeyTyped

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
        
        try {
            persona = new Persona();
            
            empleado = new Empleado();
            if (!validaciones.validarCampoVacio(numeroDocumentoEmpleadoTxt)) {
             persona.setNumeroDocumento(numeroDocumentoEmpleadoTxt.getText());
             
             
             empleado.setPersona(persona);
            
            
            if (facadeEmpleado.consultarEmpleado(empleado) != null) {
                
                empleado = facadeEmpleado.consultarEmpleado(empleado);
                
                
                nombresEmpleadoTxt.setText(empleado.getPersona().getNombres().trim()+
                        " "+empleado.getPersona().getApellidos().trim());
                
         
                registrarBtn.setEnabled(true);
                mensajeLbl.setForeground(Color.green);
                mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_EMPLEADO_ENCONTRADO);
                
                
                


            }else{
                if (!validaciones.validarCampoVacio(numeroDocumentoEmpleadoTxt)) {
                    registrarBtn.setEnabled(false);
                    mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_EMPLEADO_NO_EXISTE);
                    mensajeLbl.setForeground(Color.red);                   

                }

                

            }
            }
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(EmpleadoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        validaciones.notificarMensajeconTimer(mensajeLbl);
    }//GEN-LAST:event_consultarBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusGained

    private void descuentoServicioSeleccionadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descuentoServicioSeleccionadoTxtActionPerformed

    }//GEN-LAST:event_descuentoServicioSeleccionadoTxtActionPerformed

    private void descuentoServicioSeleccionadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descuentoServicioSeleccionadoTxtKeyTyped
        validaciones.validarSoloNumerosConEnter(evt, descuentoServicioSeleccionadoTxt);
        validaciones.validarCantidadCaracteresTexto(evt, descuentoServicioSeleccionadoTxt, 2);
    }//GEN-LAST:event_descuentoServicioSeleccionadoTxtKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (serviciosSeleccionadosTabla.getSelectedRow() > -1) {
            modeloTablaServiciosSeleccionados.removeRow(serviciosSeleccionadosTabla.getSelectedRow());
            calcularValorParcial();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void valorServicioSeleccionadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorServicioSeleccionadoTxtKeyTyped
        validaciones.validarSoloNumerosConEnter(evt, valorServicioSeleccionadoTxt);
    }//GEN-LAST:event_valorServicioSeleccionadoTxtKeyTyped

    private void tipoServicioComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoServicioComboItemStateChanged
        validarSonido(validaciones.validaCombo(tipoServicioCombo));
    }//GEN-LAST:event_tipoServicioComboItemStateChanged

    private void tipoServicioComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoServicioComboFocusLost
        validarSonido(validaciones.validaCombo(tipoServicioCombo));
    }//GEN-LAST:event_tipoServicioComboFocusLost

    private void tipoServicioComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoServicioComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoServicioComboActionPerformed

    private void valorServicioSeleccionadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorServicioSeleccionadoTxtActionPerformed
      if (valorServicioSeleccionadoTxt.getText()== null || 
          valorServicioSeleccionadoTxt.getText().trim().equals("")|| 
          Double.parseDouble(valorServicioSeleccionadoTxt.getText()) < 1 ||
          tipoServicioCombo.getSelectedItem().toString().trim().equals(constantes.CONSTANTE_COMBO_POR_DEFECTO)) {

            mensajeLbl.setForeground(Color.red);
            mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_CANTIDAD_DE_PRODUCTOS_NO_DISPONIBLE);
            validaciones.notificarMensajeconTimer(mensajeLbl);
        }else{
            
            if (descuentoServicioSeleccionadoTxt.getText().trim().equals("") ) {
                descuentoServicioSeleccionadoTxt.setText("0");
            }

            if (valorServicioSeleccionadoTxt.getText().trim().equals("") ) {
                valorServicioSeleccionadoTxt.setText("0");
            }

           
                mapeoProductoSeleccionado();
                calcularValorParcial();


        }
    }//GEN-LAST:event_valorServicioSeleccionadoTxtActionPerformed

    private void descripcionServicioSeleccionadoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionServicioSeleccionadoTxtFocusGained

        validaciones.validarEnfoque(descripcionServicioSeleccionadoTxt);
    }//GEN-LAST:event_descripcionServicioSeleccionadoTxtFocusGained

    private void descripcionServicioSeleccionadoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionServicioSeleccionadoTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(descripcionServicioSeleccionadoTxt));
    }//GEN-LAST:event_descripcionServicioSeleccionadoTxtFocusLost

    private void descripcionServicioSeleccionadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionServicioSeleccionadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionServicioSeleccionadoTxtActionPerformed

    private void descripcionServicioSeleccionadoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionServicioSeleccionadoTxtKeyPressed

    }//GEN-LAST:event_descripcionServicioSeleccionadoTxtKeyPressed

    private void descripcionServicioSeleccionadoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionServicioSeleccionadoTxtKeyReleased

    }//GEN-LAST:event_descripcionServicioSeleccionadoTxtKeyReleased

    private void descripcionServicioSeleccionadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionServicioSeleccionadoTxtKeyTyped

        
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, descripcionServicioSeleccionadoTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_descripcionServicioSeleccionadoTxtKeyTyped

    private void valorDescuentoEmpleadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorDescuentoEmpleadoTxtKeyTyped
        validaciones.validarSoloNumerosConEnter(evt, valorDescuentoEmpleadoTxt);
    }//GEN-LAST:event_valorDescuentoEmpleadoTxtKeyTyped

    private void valorDescuentoEmpleadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorDescuentoEmpleadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorDescuentoEmpleadoTxtActionPerformed

    private void numeroDocumentoEmpleadoPagoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoPagoTxtFocusGained
        validaciones.validarEnfoque(numeroDocumentoEmpleadoPagoTxt);
    }//GEN-LAST:event_numeroDocumentoEmpleadoPagoTxtFocusGained

    private void numeroDocumentoEmpleadoPagoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoPagoTxtFocusLost
        validarSonido(validaciones.validarCampoVacio(numeroDocumentoEmpleadoPagoTxt));
    }//GEN-LAST:event_numeroDocumentoEmpleadoPagoTxtFocusLost

    private void numeroDocumentoEmpleadoPagoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoPagoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoEmpleadoPagoTxtActionPerformed

    private void numeroDocumentoEmpleadoPagoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoPagoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoEmpleadoPagoTxtKeyPressed

    private void numeroDocumentoEmpleadoPagoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoPagoTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoEmpleadoPagoTxtKeyReleased

    private void numeroDocumentoEmpleadoPagoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoEmpleadoPagoTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, numeroDocumentoEmpleadoPagoTxt));
        validaciones.validarCantidadCaracteresTexto(evt, numeroDocumentoEmpleadoPagoTxt,
            constantes.CONSTANTE_CARACTERES_POR_LINEA);
    }//GEN-LAST:event_numeroDocumentoEmpleadoPagoTxtKeyTyped

    private void consultarServiciosPagarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarServiciosPagarBtnActionPerformed
       
       
                   persona = new Persona();
            
            empleado = new Empleado();
            if (!validaciones.validarCampoVacio(numeroDocumentoEmpleadoPagoTxt) &&
                 fechaInicioDate.getDate() != null && fechaFinDate.getDate() != null &&
                 fechaInicioDate.getDate().compareTo(fechaFinDate.getDate()) <= 0 ) {
             persona.setNumeroDocumento(numeroDocumentoEmpleadoPagoTxt.getText());
             
                
             empleado.setPersona(persona);
            
            try{
            if (facadeEmpleado.consultarEmpleado(empleado) != null) {
                    empleado = facadeEmpleado.consultarEmpleado(empleado);
                    nombreEmpleadoLbl.setText(empleado.getPersona().getNombres().trim()+
                        " "+empleado.getPersona().getApellidos().trim());
                    listaParametrosPagoEmpleado = pagoEmpleadoDAO.consultarServiciosPagoEmpleadonumeroDocumento
                    (numeroDocumentoEmpleadoPagoTxt.getText(),fechaInicioDate.getDate(),fechaFinDate.getDate());
                    mapearServiciosRealizados();
                    mapearTotales();

                }
            } catch (SQLException ex) {
                Logger.getLogger(NominaGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(NominaGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
             
        }
       
        
    }//GEN-LAST:event_consultarServiciosPagarBtnActionPerformed

    private void pagarNominaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarNominaBtnActionPerformed
     
        if (Double.parseDouble(totalPagoLbl.getText()) > 0) {
            pagoEmpleadoDAO.actualizarPago(numeroDocumentoEmpleadoPagoTxt.getText(),fechaInicioDate.getDate(),fechaFinDate.getDate());
             mensajeLbl.setForeground(Color.green);
             mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_PAGO_EXITOSO);
             limpiarCampos();
            
        }else{
        mensajeLbl.setForeground(Color.red);
        mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_PAGO_NO_EXITOSO);
        }
        validaciones.notificarMensajeconTimer(mensajeLbl);
        
    }//GEN-LAST:event_pagarNominaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog.setDefaultLookAndFeelDecorated(true); 
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessBlackSteelSkin");
                NominaGUI dialog = new NominaGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarBtn;
    private javax.swing.JButton consultarServiciosPagarBtn;
    private javax.swing.JTextField descripcionServicioSeleccionadoTxt;
    private javax.swing.JTextField descuentoServicioSeleccionadoTxt;
    private javax.swing.JLabel descuentoTallerLbl;
    private javax.swing.JLabel descuentosNominaLbl;
    private com.toedter.calendar.JDateChooser fechaFinDate;
    private com.toedter.calendar.JDateChooser fechaInicioDate;
    private com.toedter.calendar.JDateChooser fechaPagoDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mensajeLbl;
    private javax.swing.JLabel nombreEmpleadoLbl;
    private javax.swing.JTextField nombresEmpleadoTxt;
    private javax.swing.JTextField numeroDocumentoEmpleadoPagoTxt;
    private javax.swing.JTextField numeroDocumentoEmpleadoTxt;
    private javax.swing.JButton pagarNominaBtn;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JTable serviciosPagarTabla;
    private javax.swing.JTable serviciosSeleccionadosTabla;
    private javax.swing.JLabel subTotalPagoLbl;
    private javax.swing.JComboBox<String> tipoServicioCombo;
    private javax.swing.JLabel totalPagoLbl;
    private javax.swing.JLabel totalParcialLbl;
    private javax.swing.JTextField valorDescuentoEmpleadoTxt;
    private javax.swing.JTextField valorServicioSeleccionadoTxt;
    // End of variables declaration//GEN-END:variables

     public void validarSonido(boolean flag){
         if (flag) {
              getToolkit().beep();
             
         }else{
             
         }
     } 
     
     public PagoEmpleado mapeoPagoEmpleado(PagoEmpleado pagoEmpleado){
         pagoEmpleado = new PagoEmpleado();
         
         pagoEmpleado.setEmpleado(empleado);
         if (valorDescuentoEmpleadoTxt.getText().trim().equals("")) {
             valorDescuentoEmpleadoTxt.setText("0");
         }
         pagoEmpleado.setDescuento(Double.parseDouble(valorDescuentoEmpleadoTxt.getText()) );
         
         pagoEmpleado.setEstado(constantes.CONSTANTE_ESTADO_POR_DEFECTO);
         
         
         pagoEmpleado.setCodEmpleado(empleado.getCodEmpleado());
         pagoEmpleado.setFechaPago(fechaPagoDate.getDate());
         pagoEmpleado.setValorPago(0.0);
         
         
        return pagoEmpleado;

     }
     
     
     public void mapeoProductoSeleccionado(){
     
                Object[] servicioAgregar = new Object[4];
                servicioAgregar[0] = tipoServicioCombo.getSelectedItem().toString().trim();
                servicioAgregar[1] = valorServicioSeleccionadoTxt.getText();
                servicioAgregar[2] = validaciones.calcularDescuento(
                                     Double.parseDouble(descuentoServicioSeleccionadoTxt.getText()),
                                     Double.parseDouble(valorServicioSeleccionadoTxt.getText()) );
               servicioAgregar[3] = descripcionServicioSeleccionadoTxt.getText();
                
                modeloTablaServiciosSeleccionados.addRow(servicioAgregar);
                serviciosSeleccionadosTabla.setModel(modeloTablaServiciosSeleccionados);
     
     }
     
     public void registrarDetallePago(JTable servicios, int codigoPago) throws SQLException, ParseException{
         
         for (int i = 0; i < servicios.getRowCount(); i++) {
             DetallePago detallePago = new DetallePago();
             detallePago.setCodPago(codigoPago);
             detallePago.setTipoServicio(servicios.getValueAt(i, 0).toString());
             detallePago.setValorServicio(Double.parseDouble(servicios.getValueAt(i, 1).toString()));
             detallePago.setDescuentoServicio(Double.parseDouble(servicios.getValueAt(i, 2).toString()));
             detallePago.setDescripcion(servicios.getValueAt(i, 3).toString());
             detallePagoDAO.registrarDetallePago(detallePago);
 
             
             
   
         }
         pagoEmpleado.setCodPago(codigoPago);
         pagoEmpleado.setValorPago(Double.parseDouble(totalParcialLbl.getText()));
         facadePagoEmpleado.modificarPagoEmpleado(pagoEmpleado);
         
     
     }

    public void calcularValorParcial() {
                    acumulaTotales = 0;
                    descuento = 0;
                    for (int i = 0; i < serviciosSeleccionadosTabla.getRowCount() ; i++) {
                    descuento = descuento + Double.parseDouble(serviciosSeleccionadosTabla.getValueAt(i, 2).toString());
                    acumulaTotales = acumulaTotales + Double.parseDouble(serviciosSeleccionadosTabla.getValueAt(i, 1).toString());
                    
                }
                totalParcialLbl.setText(validaciones.calcularSubTotal(acumulaTotales, descuento)+"");
    }
    
    
    public ParametrosFactura mapearParametrosFactura(){
                ParametrosFactura parametrosFactura = new ParametrosFactura();
                
                parametrosFactura.setNombreEmpleado(nombresEmpleadoTxt.getText());
                
                parametrosFactura.setNumeroDocumentoEmpleado(numeroDocumentoEmpleadoTxt.getText());
                parametrosFactura.setProductosaVender(modeloTablaServiciosSeleccionados);
                //parametrosFactura.setCodigoVenta(codigoVentaParametroFactura);
    return parametrosFactura;
    }
    
    public void mapearServiciosRealizados(){
         modeloTablaServiciosPagar = new DefaultTableModel();
        modeloTablaServiciosPagar.setColumnIdentifiers(columnasTablaPagoServicios);
                for (int i = 0; i < listaParametrosPagoEmpleado.size(); i++) {
            Object [] registro = new Object[5];
            registro[0] = listaParametrosPagoEmpleado.get(i).getServicio().toString().trim();
            registro[1] = listaParametrosPagoEmpleado.get(i).getDescripcion().toString().trim();
            registro[2] = listaParametrosPagoEmpleado.get(i).getValorServicio();
            registro[3] = listaParametrosPagoEmpleado.get(i).getDescuentoServicio();
            registro[4] = listaParametrosPagoEmpleado.get(i).getFechaServicio();
            modeloTablaServiciosPagar.addRow(registro);
        }
    serviciosPagarTabla.setModel(modeloTablaServiciosPagar);
    }
    
    public void mapearTotales(){
                            
                    
                    listadoTotalesPago = pagoEmpleadoDAO.consultarTotalesPago
                    (numeroDocumentoEmpleadoPagoTxt.getText(), fechaInicioDate.getDate(), fechaFinDate.getDate());
                    
                    for (int i = 0; i < listadoTotalesPago.size(); i++) {
                        if (i == 0) {
                            descuentosNominaLbl.setText(listadoTotalesPago.get(i).toString());
                        }else if(i == 1){
                        subTotalPagoLbl.setText(listadoTotalesPago.get(i).toString());
                        
                        }
                        
                }
                    descuentoTallerLbl.setText((Double.parseDouble(subTotalPagoLbl.getText())*0.25)+"");
                    totalPagoLbl.setText(Double.parseDouble(subTotalPagoLbl.getText())-
                    (Double.parseDouble(descuentosNominaLbl.getText())+Double.parseDouble(descuentoTallerLbl.getText()))+"");
                    pagarNominaBtn.setVisible(true);
    }

    private void limpiarCampos() {
        numeroDocumentoEmpleadoTxt.setText("");
        nombresEmpleadoTxt.setText("");
        fechaPagoDate.setDate(null);
        valorDescuentoEmpleadoTxt.setText("");
        tipoServicioCombo.setSelectedItem(constantes.CONSTANTE_COMBO_POR_DEFECTO);
        descripcionServicioSeleccionadoTxt.setText("");
        descuentoServicioSeleccionadoTxt.setText("");
        valorServicioSeleccionadoTxt.setText("");
        modeloTablaServiciosSeleccionados = new DefaultTableModel();
        modeloTablaServiciosPagar = new DefaultTableModel();
        modeloTablaServiciosSeleccionados.setColumnIdentifiers(columnasTablaServiciosSeleccionados);
        modeloTablaServiciosPagar.setColumnIdentifiers(columnasTablaPagoServicios);
        serviciosSeleccionadosTabla.setModel(modeloTablaServiciosSeleccionados);
        serviciosPagarTabla.setModel(modeloTablaServiciosPagar);
        numeroDocumentoEmpleadoPagoTxt.setText("");
        nombreEmpleadoLbl.setText("");
        fechaInicioDate.setDate(null);
        fechaFinDate.setDate(null);
        subTotalPagoLbl.setText("");
        descuentosNominaLbl.setText("");
        descuentoTallerLbl.setText("");
        totalPagoLbl.setText("");
        totalParcialLbl.setText("");
    }



}
