/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ConstantesAlmacenyTaller;
import Control.TipoDocumentoDAO;
import Control.Validaciones;
import Facade.FacadePersona;
import Facade.FacadeProveedor;
import Modelo.Persona;
import Modelo.Proveedor;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import static javax.swing.JDialog.setDefaultLookAndFeelDecorated;
import javax.swing.JFrame;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author jose luis Rodriguez
 */
public class ProveedorGUI extends javax.swing.JDialog {
    
    Validaciones validaciones = new Validaciones();
    TipoDocumentoDAO tipoDocumentoDAO = new TipoDocumentoDAO();
    ConstantesAlmacenyTaller constantes = new ConstantesAlmacenyTaller();
    FacadeProveedor facadeProveedor = new FacadeProveedor();
    FacadePersona facadePersona = new FacadePersona();
    Proveedor proveedor = new Proveedor();
    Persona persona = new Persona();
    
    /**
     * Creates new form EmpleadoGUI
     */
    public ProveedorGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        validaciones.adicionarItems(tipoDocumentoCombo,
        tipoDocumentoDAO.consultarTiposDocumento());
        this.setTitle("Gestion Empleados");
        this.setLocationRelativeTo(null);        
        registrarBtn.setEnabled(false);
        modificarBtn.setEnabled(false);
        paisTxt.setText(constantes.CONSTANTE_PAIS_POR_DEFECTO);
        paisTxt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGenero = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nombresTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        apellidosTxt = new javax.swing.JTextField();
        direccionTxt = new javax.swing.JTextField();
        tipoDocumentoCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        numeroDocumentoTxt = new javax.swing.JTextField();
        celularTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        razonSocialTxt = new javax.swing.JTextField();
        telefonoEmpresaTxt = new javax.swing.JTextField();
        faxTxt = new javax.swing.JTextField();
        correoComercialTxt = new javax.swing.JTextField();
        paisTxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jRadioButtonOtro = new javax.swing.JRadioButton();
        paginaWebTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mensajeLbl = new javax.swing.JLabel();
        registrarBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        consultarBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombresTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nombresTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        nombresTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresTxtFocusLost(evt);
            }
        });
        nombresTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresTxtActionPerformed(evt);
            }
        });
        nombresTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombresTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombresTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresTxtKeyTyped(evt);
            }
        });
        jPanel1.add(nombresTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("Apellidos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, 10));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Nombres");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, 10));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setText("Dirección");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 10));

        telefonoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        telefonoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        telefonoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoTxtFocusLost(evt);
            }
        });
        telefonoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTxtActionPerformed(evt);
            }
        });
        telefonoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyTyped(evt);
            }
        });
        jPanel1.add(telefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 180, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setText("Celular");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        apellidosTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        apellidosTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        apellidosTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apellidosTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apellidosTxtFocusLost(evt);
            }
        });
        apellidosTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosTxtActionPerformed(evt);
            }
        });
        apellidosTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apellidosTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                apellidosTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidosTxtKeyTyped(evt);
            }
        });
        jPanel1.add(apellidosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        direccionTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        direccionTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        direccionTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                direccionTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                direccionTxtFocusLost(evt);
            }
        });
        direccionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTxtActionPerformed(evt);
            }
        });
        direccionTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                direccionTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                direccionTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionTxtKeyTyped(evt);
            }
        });
        jPanel1.add(direccionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 180, -1));

        tipoDocumentoCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tipoDocumentoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --" }));
        tipoDocumentoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoDocumentoComboItemStateChanged(evt);
            }
        });
        tipoDocumentoCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tipoDocumentoComboFocusLost(evt);
            }
        });
        tipoDocumentoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDocumentoComboActionPerformed(evt);
            }
        });
        jPanel1.add(tipoDocumentoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("Numero de Documento");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, 10));

        numeroDocumentoTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        numeroDocumentoTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        numeroDocumentoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroDocumentoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroDocumentoTxtFocusLost(evt);
            }
        });
        numeroDocumentoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDocumentoTxtActionPerformed(evt);
            }
        });
        numeroDocumentoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroDocumentoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroDocumentoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDocumentoTxtKeyTyped(evt);
            }
        });
        jPanel1.add(numeroDocumentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, -1));

        celularTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        celularTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        celularTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                celularTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                celularTxtFocusLost(evt);
            }
        });
        celularTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularTxtActionPerformed(evt);
            }
        });
        celularTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                celularTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                celularTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celularTxtKeyTyped(evt);
            }
        });
        jPanel1.add(celularTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("Tipo de Documento");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel11.setText("Telefono");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, 10));

        jTabbedPane1.addTab("Información Representante Legal", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel18.setText("Razon Social");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 10));

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel20.setText("Correo Comercial");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel26.setText("Telefono Empresa");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        razonSocialTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        razonSocialTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        razonSocialTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                razonSocialTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                razonSocialTxtFocusLost(evt);
            }
        });
        razonSocialTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razonSocialTxtActionPerformed(evt);
            }
        });
        razonSocialTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                razonSocialTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                razonSocialTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                razonSocialTxtKeyTyped(evt);
            }
        });
        jPanel2.add(razonSocialTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, -1));

        telefonoEmpresaTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        telefonoEmpresaTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        telefonoEmpresaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoEmpresaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoEmpresaTxtFocusLost(evt);
            }
        });
        telefonoEmpresaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoEmpresaTxtActionPerformed(evt);
            }
        });
        telefonoEmpresaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoEmpresaTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefonoEmpresaTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoEmpresaTxtKeyTyped(evt);
            }
        });
        jPanel2.add(telefonoEmpresaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, -1));

        faxTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        faxTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        faxTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                faxTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                faxTxtFocusLost(evt);
            }
        });
        faxTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxTxtActionPerformed(evt);
            }
        });
        faxTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                faxTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                faxTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                faxTxtKeyTyped(evt);
            }
        });
        jPanel2.add(faxTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, -1));

        correoComercialTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        correoComercialTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        correoComercialTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correoComercialTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                correoComercialTxtFocusLost(evt);
            }
        });
        correoComercialTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoComercialTxtActionPerformed(evt);
            }
        });
        correoComercialTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                correoComercialTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                correoComercialTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoComercialTxtKeyTyped(evt);
            }
        });
        jPanel2.add(correoComercialTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

        paisTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        paisTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        paisTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paisTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paisTxtFocusLost(evt);
            }
        });
        paisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisTxtActionPerformed(evt);
            }
        });
        paisTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paisTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paisTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paisTxtKeyTyped(evt);
            }
        });
        jPanel2.add(paisTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, -1));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel23.setText("Pais");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, 10));

        jRadioButtonOtro.setText("Otro?");
        jRadioButtonOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOtroActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        paginaWebTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        paginaWebTxt.setMaximumSize(new java.awt.Dimension(6, 10));
        paginaWebTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paginaWebTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paginaWebTxtFocusLost(evt);
            }
        });
        paginaWebTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginaWebTxtActionPerformed(evt);
            }
        });
        paginaWebTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paginaWebTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paginaWebTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paginaWebTxtKeyTyped(evt);
            }
        });
        jPanel2.add(paginaWebTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 180, -1));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setText("Fax");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel24.setText("Pagina Web");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("*");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 10));

        jTabbedPane1.addTab("Información Laboral", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 490, 350));

        jLabel12.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores.png"))); // NOI18N
        jLabel12.setText("Proveedores");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 310, 80));

        mensajeLbl.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        mensajeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mensajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 350, 30));

        registrarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        registrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        registrarBtn.setToolTipText("REGISTRAR");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(registrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 145, 55));

        modificarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        modificarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        modificarBtn.setToolTipText("MODIFICAR");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 145, 55));

        consultarBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        consultarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        consultarBtn.setToolTipText("CONSULTAR");
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(consultarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 145, 55));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        jButton3.setToolTipText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 145, 55));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresTxtFocusGained

        validaciones.validarEnfoque(nombresTxt);
    }//GEN-LAST:event_nombresTxtFocusGained

    private void nombresTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(nombresTxt));
    }//GEN-LAST:event_nombresTxtFocusLost

    private void nombresTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresTxtActionPerformed

    private void nombresTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresTxtKeyPressed

    }//GEN-LAST:event_nombresTxtKeyPressed

    private void nombresTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresTxtKeyReleased

    }//GEN-LAST:event_nombresTxtKeyReleased

    private void nombresTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, nombresTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, nombresTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_nombresTxtKeyTyped

    private void telefonoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTxtFocusGained
        validaciones.validarEnfoque(telefonoTxt);
    }//GEN-LAST:event_telefonoTxtFocusGained

    private void telefonoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTxtFocusLost
        
    }//GEN-LAST:event_telefonoTxtFocusLost

    private void telefonoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTxtActionPerformed

    private void telefonoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTxtKeyPressed

    private void telefonoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTxtKeyReleased

    private void telefonoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, telefonoTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, telefonoTxt,
            constantes.CONSTANTE_VALOR_POR_DEFECTO);
    }//GEN-LAST:event_telefonoTxtKeyTyped

    private void apellidosTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidosTxtFocusGained

        validaciones.validarEnfoque(apellidosTxt);
    }//GEN-LAST:event_apellidosTxtFocusGained

    private void apellidosTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidosTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(apellidosTxt));
    }//GEN-LAST:event_apellidosTxtFocusLost

    private void apellidosTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosTxtActionPerformed

    private void apellidosTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosTxtKeyPressed

    }//GEN-LAST:event_apellidosTxtKeyPressed

    private void apellidosTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosTxtKeyReleased

    }//GEN-LAST:event_apellidosTxtKeyReleased

    private void apellidosTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, apellidosTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, apellidosTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_apellidosTxtKeyTyped

    private void direccionTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTxtFocusGained

        validaciones.validarEnfoque(direccionTxt);
    }//GEN-LAST:event_direccionTxtFocusGained

    private void direccionTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(direccionTxt));
    }//GEN-LAST:event_direccionTxtFocusLost

    private void direccionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTxtActionPerformed

    private void direccionTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyPressed

    }//GEN-LAST:event_direccionTxtKeyPressed

    private void direccionTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyReleased

    }//GEN-LAST:event_direccionTxtKeyReleased

    private void direccionTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyTyped

        
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, direccionTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_direccionTxtKeyTyped

    private void tipoDocumentoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoDocumentoComboItemStateChanged
        validarSonido(validaciones.validaCombo(tipoDocumentoCombo));
    }//GEN-LAST:event_tipoDocumentoComboItemStateChanged

    private void tipoDocumentoComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoDocumentoComboFocusLost
        validarSonido(validaciones.validaCombo(tipoDocumentoCombo));
    }//GEN-LAST:event_tipoDocumentoComboFocusLost

    private void tipoDocumentoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDocumentoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDocumentoComboActionPerformed

    private void numeroDocumentoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtFocusGained
        validaciones.validarEnfoque(numeroDocumentoTxt);
    }//GEN-LAST:event_numeroDocumentoTxtFocusGained

    private void numeroDocumentoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtFocusLost
        validarSonido(validaciones.validarCampoVacio(numeroDocumentoTxt));
    }//GEN-LAST:event_numeroDocumentoTxtFocusLost

    private void numeroDocumentoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoTxtActionPerformed

    private void numeroDocumentoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoTxtKeyPressed

    private void numeroDocumentoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDocumentoTxtKeyReleased

    private void numeroDocumentoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDocumentoTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, numeroDocumentoTxt));
        validaciones.validarCantidadCaracteresTexto(evt, numeroDocumentoTxt,
            constantes.CONSTANTE_CARACTERES_POR_LINEA);
    }//GEN-LAST:event_numeroDocumentoTxtKeyTyped

    private void celularTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celularTxtFocusGained
        validaciones.validarEnfoque(celularTxt);
    }//GEN-LAST:event_celularTxtFocusGained

    private void celularTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celularTxtFocusLost
       
    }//GEN-LAST:event_celularTxtFocusLost

    private void celularTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularTxtActionPerformed

    private void celularTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularTxtKeyPressed

    private void celularTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_celularTxtKeyReleased

    private void celularTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, celularTxt));
        validaciones.validarCantidadCaracteresTexto(evt, celularTxt,
            constantes.CONSTANTE_VALOR_POR_DEFECTO);
    }//GEN-LAST:event_celularTxtKeyTyped

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed

        try {
            proveedor = new Proveedor();
            persona = new Persona();
            persona.setNumeroDocumento(numeroDocumentoTxt.getText());
            proveedor.setPersona(persona);
            
        if (validaciones.validarCamposProveedor(nombresTxt, apellidosTxt, tipoDocumentoCombo,
                numeroDocumentoTxt, direccionTxt, razonSocialTxt, paisTxt).equals("") && 
                facadeProveedor.consultarProveedor(proveedor) == null) {

                    facadeProveedor.registrarProveedor(mapearProveedor());
                    
        }else{
            mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_POR_DEFECTO);
                    
    }
            validaciones.notificarMensajeconTimer(mensajeLbl);

    }   catch (SQLException | ParseException ex) {
            Logger.getLogger(ProveedorGUI.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
        
        try {
           
            proveedor = new Proveedor();
            persona = new Persona();
            persona.setNumeroDocumento(numeroDocumentoTxt.getText());
            proveedor.setPersona(persona);
            if (!validaciones.validarCampoVacio(numeroDocumentoTxt) &&
                facadeProveedor.consultarProveedor(proveedor) != null ) {
                proveedor = facadeProveedor.consultarProveedor(proveedor);
                validaciones.mapearProveedor(proveedor, nombresTxt, apellidosTxt, tipoDocumentoCombo,
                                             numeroDocumentoTxt, direccionTxt, telefonoTxt, celularTxt,
                                             razonSocialTxt, paisTxt, telefonoEmpresaTxt, paginaWebTxt, faxTxt,
                                             correoComercialTxt, jRadioButtonOtro);
                registrarBtn.setEnabled(false);
                modificarBtn.setEnabled(true);
            }else{
                if (!validaciones.validarCampoVacio(numeroDocumentoTxt)) {
                registrarBtn.setEnabled(true);
                modificarBtn.setEnabled(false);
                }
                
            }

        } catch (SQLException | ParseException ex) {
            Logger.getLogger(ProveedorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_consultarBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
     
        try {
            
                        if (validaciones.validarCamposProveedor(nombresTxt, apellidosTxt,
                            tipoDocumentoCombo, numeroDocumentoTxt, direccionTxt, razonSocialTxt,
                            paisTxt).equals("")){
                        mensajeLbl.setText(facadeProveedor.modificarProveedor(mapearProveedor()));
                        
                        }else{
                        
                        mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_POR_DEFECTO);
                        
                        }
            
            
            validaciones.notificarMensajeconTimer(mensajeLbl);

        } catch (SQLException | ParseException ex) {
            Logger.getLogger(ProductoGUIJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        validaciones.limpiarCamposProveedor(nombresTxt, apellidosTxt, tipoDocumentoCombo,
                                            numeroDocumentoTxt, direccionTxt, telefonoTxt,
                                            celularTxt, razonSocialTxt, paisTxt,
                                            telefonoEmpresaTxt, paginaWebTxt, faxTxt,
                                            correoComercialTxt, jRadioButtonOtro);
        modificarBtn.setEnabled(false);
        registrarBtn.setEnabled(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void razonSocialTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_razonSocialTxtFocusGained

        validaciones.validarEnfoque(razonSocialTxt);
    }//GEN-LAST:event_razonSocialTxtFocusGained

    private void razonSocialTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_razonSocialTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(razonSocialTxt));
    }//GEN-LAST:event_razonSocialTxtFocusLost

    private void razonSocialTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razonSocialTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razonSocialTxtActionPerformed

    private void razonSocialTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_razonSocialTxtKeyPressed

    }//GEN-LAST:event_razonSocialTxtKeyPressed

    private void razonSocialTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_razonSocialTxtKeyReleased

    }//GEN-LAST:event_razonSocialTxtKeyReleased

    private void razonSocialTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_razonSocialTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, razonSocialTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, razonSocialTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_razonSocialTxtKeyTyped

    private void telefonoEmpresaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoEmpresaTxtFocusGained
        validaciones.validarEnfoque(telefonoEmpresaTxt);
    }//GEN-LAST:event_telefonoEmpresaTxtFocusGained

    private void telefonoEmpresaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoEmpresaTxtFocusLost
        validarSonido(validaciones.validarCampoVacio(telefonoEmpresaTxt));
    }//GEN-LAST:event_telefonoEmpresaTxtFocusLost

    private void telefonoEmpresaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoEmpresaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoEmpresaTxtActionPerformed

    private void telefonoEmpresaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoEmpresaTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoEmpresaTxtKeyPressed

    private void telefonoEmpresaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoEmpresaTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoEmpresaTxtKeyReleased

    private void telefonoEmpresaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoEmpresaTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, telefonoEmpresaTxt));
        validaciones.validarCantidadCaracteresTexto(evt, telefonoEmpresaTxt,
            constantes.CONSTANTE_NUMEROS_TELEFONICOS);
    }//GEN-LAST:event_telefonoEmpresaTxtKeyTyped

    private void faxTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_faxTxtFocusGained
        validaciones.validarEnfoque(faxTxt);
    }//GEN-LAST:event_faxTxtFocusGained

    private void faxTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_faxTxtFocusLost
     
    }//GEN-LAST:event_faxTxtFocusLost

    private void faxTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faxTxtActionPerformed

    private void faxTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faxTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_faxTxtKeyPressed

    private void faxTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faxTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_faxTxtKeyReleased

    private void faxTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faxTxtKeyTyped
        validarSonido(validaciones.validarSoloNumeros(evt, faxTxt));
        validaciones.validarCantidadCaracteresTexto(evt, faxTxt,
            constantes.CONSTANTE_NUMEROS_TELEFONICOS);
    }//GEN-LAST:event_faxTxtKeyTyped

    private void correoComercialTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoComercialTxtFocusGained

        validaciones.validarEnfoque(correoComercialTxt);
    }//GEN-LAST:event_correoComercialTxtFocusGained

    private void correoComercialTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoComercialTxtFocusLost
        if (!correoComercialTxt.getText().trim().equals("") && correoComercialTxt.getText() != null) {
             if (!validaciones.validarEmail(correoComercialTxt.getText())) {
                     mensajeLbl.setText(constantes.CONSTANTE_MENSAJE_VALIDACION_EMAIL);
                     validaciones.notificarMensajeconTimer(mensajeLbl);
                     mensajeLbl.setForeground(Color.red);
                     validarSonido(true);
                     }   
        }
    }//GEN-LAST:event_correoComercialTxtFocusLost

    private void correoComercialTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoComercialTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoComercialTxtActionPerformed

    private void correoComercialTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoComercialTxtKeyPressed

    }//GEN-LAST:event_correoComercialTxtKeyPressed

    private void correoComercialTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoComercialTxtKeyReleased

    }//GEN-LAST:event_correoComercialTxtKeyReleased

    private void correoComercialTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoComercialTxtKeyTyped

        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, correoComercialTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_correoComercialTxtKeyTyped

    private void paisTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paisTxtFocusGained

        validaciones.validarEnfoque(paisTxt);
    }//GEN-LAST:event_paisTxtFocusGained

    private void paisTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paisTxtFocusLost

        validarSonido(validaciones.validarCampoVacio(paisTxt));
    }//GEN-LAST:event_paisTxtFocusLost

    private void paisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisTxtActionPerformed

    private void paisTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisTxtKeyPressed

    }//GEN-LAST:event_paisTxtKeyPressed

    private void paisTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisTxtKeyReleased

    }//GEN-LAST:event_paisTxtKeyReleased

    private void paisTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisTxtKeyTyped

        validarSonido(validaciones.validarSoloLetras(evt, paisTxt));
        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, paisTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_paisTxtKeyTyped

    private void jRadioButtonOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOtroActionPerformed
        if (jRadioButtonOtro.isSelected()) {
            paisTxt.setEnabled(true);
            paisTxt.setText("");
            paisTxt.setBackground(Color.white);
        }else{
            paisTxt.setEnabled(false);
            paisTxt.setText(validaciones.CONSTANTE_PAIS_POR_DEFECTO);
        }

    }//GEN-LAST:event_jRadioButtonOtroActionPerformed

    private void paginaWebTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paginaWebTxtFocusGained

        validaciones.validarEnfoque(paginaWebTxt);
    }//GEN-LAST:event_paginaWebTxtFocusGained

    private void paginaWebTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paginaWebTxtFocusLost

      
    }//GEN-LAST:event_paginaWebTxtFocusLost

    private void paginaWebTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginaWebTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paginaWebTxtActionPerformed

    private void paginaWebTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paginaWebTxtKeyPressed

    }//GEN-LAST:event_paginaWebTxtKeyPressed

    private void paginaWebTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paginaWebTxtKeyReleased

    }//GEN-LAST:event_paginaWebTxtKeyReleased

    private void paginaWebTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paginaWebTxtKeyTyped

        validaciones.minusculaToMayuscula(evt);
        validaciones.validarCantidadCaracteresTexto(evt, paginaWebTxt,
            constantes.CONSTANTE_TEXTO_POR_DEFECTO);
    }//GEN-LAST:event_paginaWebTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog.setDefaultLookAndFeelDecorated(true); 
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessBlackSteelSkin");
                ProveedorGUI dialog = new ProveedorGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
 
               
                dialog.setVisible(true);
            }
        });
    }
    
         public void validarSonido(boolean flag){
         if (flag) {
              getToolkit().beep();
             
         }else{
             
         }
     } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosTxt;
    private javax.swing.ButtonGroup buttonGroupGenero;
    private javax.swing.JTextField celularTxt;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JTextField correoComercialTxt;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JTextField faxTxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonOtro;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mensajeLbl;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JTextField nombresTxt;
    private javax.swing.JTextField numeroDocumentoTxt;
    private javax.swing.JTextField paginaWebTxt;
    private javax.swing.JTextField paisTxt;
    private javax.swing.JTextField razonSocialTxt;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JTextField telefonoEmpresaTxt;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JComboBox<String> tipoDocumentoCombo;
    // End of variables declaration//GEN-END:variables

    private Proveedor mapearProveedor() {
        
        persona.setNombres(nombresTxt.getText().trim());
        persona.setApellidos(apellidosTxt.getText().trim());
        persona.setTelefono(telefonoTxt.getText().trim());
        persona.setCelular(celularTxt.getText().trim());
        persona.setTipoDocumento(tipoDocumentoCombo.getSelectedItem().toString());
        persona.setNumeroDocumento(numeroDocumentoTxt.getText().trim());
        persona.setDireccion(direccionTxt.getText().trim());
        proveedor.setPersona(persona);
        proveedor.setEmailComercial(correoComercialTxt.getText());
        proveedor.setFax(faxTxt.getText());
        proveedor.setPaginaWeb(paginaWebTxt.getText());
        proveedor.setPais(paisTxt.getText());
        proveedor.setRazonSocial(razonSocialTxt.getText());
        proveedor.setTelefonoEmpresa(telefonoEmpresaTxt.getText());
        proveedor.setEstado(constantes.CONSTANTE_ESTADO_POR_DEFECTO);
        

        
        return proveedor;
        
        
    }
}
